import type { Product } from './types';

/**
 * Product catalogue.
 *
 * DATA RULE — read before editing.
 *
 * Product names and category placements come from the partners' own published
 * catalogues (walchem.com, timex.com.tr, kurita.eu). No capacity, flow rate,
 * filtration degree, pressure rating, dose rate, material or performance
 * figure has been entered, because none of those are verifiable from public
 * sources at the level of confidence a technical buyer is entitled to.
 *
 * The `specs` array therefore holds only definitional rows — what the product
 * *is*, not how it performs — and `specsPendingReview` is true on every record
 * whose performance data is still outstanding. Those pages render the
 * "Technical information available on request" state instead of a specification
 * table. Populate `specs` from approved partner documentation and flip the flag
 * once C-Water has signed the data off.
 *
 * Documents are declared with `file: null` and `availableOnRequest: true` until
 * the actual PDFs are supplied and the distribution rights confirmed.
 */

const onRequestDoc = (id: string, en: string, ar: string, kind: Product['documents'][number]['kind']) => ({
  id,
  title: { en, ar },
  kind,
  file: null,
  size: null,
  availableOnRequest: true,
});

export const products: Product[] = [
  /* ================= WALCHEM — CONTROLLERS ============================== */
  {
    slug: 'walchem-intuition-9',
    status: 'published',
    name: 'Walchem Intuition-9',
    partner: 'walchem',
    category: 'controllers',
    technology: 'monitoring-control',
    title: { en: 'Intuition-9 Water Treatment Controller', ar: 'وحدة تحكم Intuition-9 لمعالجة المياه' },
    positioning: {
      en: 'Multi-input analytical controller for water systems that need more than one measurement acting together.',
      ar: 'وحدة تحكم تحليلية متعددة المداخل لأنظمة المياه التي تحتاج أكثر من قياس يعمل معًا.',
    },
    summary: {
      en: 'Walchem’s multi-parameter controller platform for cooling, boiler and general water-treatment control.',
      ar: 'منصة وحدات التحكم متعددة المتغيرات من Walchem للتحكم في التبريد والغلايات ومعالجة المياه عمومًا.',
    },
    metaTitle: { en: 'Walchem Intuition-9 Controller | C-Water', ar: 'وحدة تحكم Walchem Intuition-9 | C-Water' },
    metaDescription: {
      en: 'The Walchem Intuition-9 water treatment controller, applied and commissioned by C-Water engineering for cooling, boiler and multi-system water treatment control.',
      ar: 'وحدة تحكم Walchem Intuition-9 لمعالجة المياه، تطبّقها وتشغّلها هندسة C-Water للتحكم في التبريد والغلايات وأنظمة المعالجة المتعددة.',
    },
    overview: {
      en: 'Intuition-9 is Walchem’s higher-capability analytical controller, intended for systems where several measured parameters, several control outputs and a data record are required from one device. C-Water applies it where a single-parameter controller would leave part of the treatment programme uncontrolled.',
      ar: 'Intuition-9 هي وحدة التحكم التحليلية الأعلى قدرة لدى Walchem، ومخصصة للأنظمة التي تتطلب عدة متغيرات مقاسة وعدة مخارج تحكم وسجل بيانات من جهاز واحد. وتستخدمها C-Water حيث تترك وحدة أحادية المتغير جزءًا من برنامج المعالجة بلا تحكم.',
    },
    benefits: [
      { id: 'multi', icon: 'controller', label: { en: 'One device, several loops', ar: 'جهاز واحد لعدة حلقات' }, body: { en: 'Conductivity, pH, ORP and flow-based control handled together rather than by separate uncoordinated devices.', ar: 'يتعامل مع التحكم القائم على التوصيلية وpH وORP والتدفق معًا بدلًا من أجهزة منفصلة غير منسقة.' } },
      { id: 'record', icon: 'monitor', label: { en: 'A record of what happened', ar: 'سجل لما حدث' }, body: { en: 'Logged data and trends make it possible to investigate a deviation after the fact instead of guessing.', ar: 'تتيح البيانات والاتجاهات المسجلة التحقيق في انحراف بعد وقوعه بدلًا من التخمين.' } },
      { id: 'verify', icon: 'shield', label: { en: 'Feed verification', ar: 'التحقق من الضخ' }, body: { en: 'Confirms that a call for chemical actually resulted in chemical being delivered.', ar: 'يؤكد أن طلب الكيماوي أدى فعلًا إلى ضخه.' } },
      { id: 'connect', icon: 'network', label: { en: 'Remote visibility', ar: 'رؤية عن بُعد' }, body: { en: 'Connects into remote monitoring so a condition can be seen without a site visit.', ar: 'يتصل بالمراقبة عن بُعد لرؤية أي حالة دون زيارة الموقع.' } },
    ],
    applications: [
      { en: 'Cooling tower control', ar: 'التحكم في أبراج التبريد' },
      { en: 'Boiler blowdown and chemical feed', ar: 'تصريف الغلايات وضخ الكيماويات' },
      { en: 'Multi-system plant supervision', ar: 'الإشراف على أنظمة متعددة' },
      { en: 'Process water monitoring', ar: 'مراقبة مياه العمليات' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'Walchem Intuition series', ar: 'سلسلة Walchem Intuition' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Online analytical water treatment controller', ar: 'وحدة تحكم تحليلية متصلة لمعالجة المياه' } },
      { key: { en: 'Typical measured parameters', ar: 'المتغيرات المقاسة المعتادة' }, value: { en: 'Conductivity, pH, ORP, flow, level', ar: 'التوصيلية، pH، ORP، التدفق، المستوى' } },
    ],
    specsPendingReview: true,
    documents: [
      onRequestDoc('ds', 'Intuition-9 datasheet', 'ورقة بيانات Intuition-9', 'datasheet'),
      onRequestDoc('man', 'Installation and operating manual', 'دليل التركيب والتشغيل', 'technical-guide'),
    ],
    solutions: ['cooling-water', 'boiler-steam', 'industrial-water', 'process-water', 'wastewater'],
    industries: ['manufacturing', 'power-utilities', 'chemical-petrochemical', 'food-beverage', 'pharmaceutical-cosmetics'],
    relatedProducts: ['walchem-intuition-6', 'walchem-conductivity-sensors', 'walchem-ph-orp-sensors', 'walchem-fluent'],
  },

  {
    slug: 'walchem-intuition-6',
    status: 'published',
    name: 'Walchem Intuition-6',
    partner: 'walchem',
    category: 'controllers',
    technology: 'monitoring-control',
    title: { en: 'Intuition-6 Water Treatment Controller', ar: 'وحدة تحكم Intuition-6 لمعالجة المياه' },
    positioning: { en: 'Analytical controller for single-system cooling and general water-treatment duty.', ar: 'وحدة تحكم تحليلية لتطبيقات التبريد أحادية النظام ومعالجة المياه عمومًا.' },
    summary: { en: 'A focused controller for systems that need reliable measurement and control without multi-loop complexity.', ar: 'وحدة تحكم مركّزة للأنظمة التي تحتاج قياسًا وتحكمًا موثوقين دون تعقيد الحلقات المتعددة.' },
    metaTitle: { en: 'Walchem Intuition-6 Controller | C-Water', ar: 'وحدة تحكم Walchem Intuition-6 | C-Water' },
    metaDescription: { en: 'The Walchem Intuition-6 water treatment controller for cooling tower and general water treatment control, specified and commissioned by C-Water.', ar: 'وحدة تحكم Walchem Intuition-6 لمعالجة المياه لأبراج التبريد ومعالجة المياه عمومًا، تحدد مواصفاتها وتشغّلها C-Water.' },
    overview: {
      en: 'Where a system needs proper measured control but not the input count of a larger platform, Intuition-6 keeps the control philosophy intact without paying for capability that will never be configured.',
      ar: 'حيث يحتاج النظام تحكمًا مقاسًا سليمًا دون عدد المداخل الكبير لمنصة أكبر، تحافظ Intuition-6 على فلسفة التحكم دون دفع ثمن قدرات لن تُستخدم أبدًا.',
    },
    benefits: [
      { id: 'right-size', icon: 'gauge', label: { en: 'Sized to the duty', ar: 'بحجم يناسب المهمة' }, body: { en: 'Full control capability for the parameters a single cooling or utility system actually needs.', ar: 'قدرة تحكم كاملة للمتغيرات التي يحتاجها فعلًا نظام تبريد أو مرافق منفرد.' } },
      { id: 'simple', icon: 'controller', label: { en: 'Operable by site staff', ar: 'قابلة للتشغيل من فريق الموقع' }, body: { en: 'A configuration the maintenance team can understand is a configuration that stays correct.', ar: 'التهيئة التي يفهمها فريق الصيانة هي التهيئة التي تبقى صحيحة.' } },
      { id: 'connect', icon: 'network', label: { en: 'Remote capable', ar: 'قابلة للمراقبة عن بُعد' }, body: { en: 'Supports connected monitoring for sites without permanent technical attendance.', ar: 'تدعم المراقبة المتصلة للمواقع التي لا يوجد بها إشراف فني دائم.' } },
    ],
    applications: [
      { en: 'Cooling tower control', ar: 'التحكم في أبراج التبريد' },
      { en: 'Commercial HVAC water systems', ar: 'أنظمة مياه التكييف التجارية' },
      { en: 'General water treatment control', ar: 'التحكم العام في معالجة المياه' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'Walchem Intuition series', ar: 'سلسلة Walchem Intuition' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Online analytical water treatment controller', ar: 'وحدة تحكم تحليلية متصلة لمعالجة المياه' } },
      { key: { en: 'Variants published by Walchem', ar: 'الإصدارات المنشورة من Walchem' }, value: { en: 'Intuition-6, Intuition-6 Copper/Nickel, WPD Intuition-6', ar: 'Intuition-6، Intuition-6 Copper/Nickel، WPD Intuition-6' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Intuition-6 datasheet', 'ورقة بيانات Intuition-6', 'datasheet')],
    solutions: ['cooling-water', 'boiler-steam', 'potable-water'],
    industries: ['hospitality', 'commercial-buildings', 'healthcare', 'manufacturing', 'aquaculture'],
    relatedProducts: ['walchem-intuition-9', 'walchem-w100', 'walchem-conductivity-sensors'],
  },

  {
    slug: 'walchem-w100',
    status: 'published',
    name: 'Walchem W100W',
    partner: 'walchem',
    category: 'controllers',
    technology: 'monitoring-control',
    title: { en: 'W100W Controller', ar: 'وحدة تحكم W100W' },
    positioning: { en: 'Compact controller for straightforward conductivity-based control duty.', ar: 'وحدة تحكم مدمجة لمهام التحكم المباشر المعتمد على التوصيلية.' },
    summary: { en: 'A simple, robust controller where the control requirement is a single measured parameter.', ar: 'وحدة تحكم بسيطة ومتينة حيث يكون متطلب التحكم متغيرًا مقاسًا واحدًا.' },
    metaTitle: { en: 'Walchem W100W Controller | C-Water', ar: 'وحدة تحكم Walchem W100W | C-Water' },
    metaDescription: { en: 'The Walchem W100W controller for conductivity-based blowdown and chemical feed control in boiler and cooling water systems.', ar: 'وحدة تحكم Walchem W100W للتحكم في التصريف وضخ الكيماويات وفق التوصيلية في أنظمة الغلايات ومياه التبريد.' },
    overview: {
      en: 'Not every system needs a multi-parameter platform. Where the requirement is conductivity-driven blowdown and a chemical feed output, a compact controller does the job and stays configured.',
      ar: 'ليست كل الأنظمة بحاجة إلى منصة متعددة المتغيرات. فحيث يكون المطلوب تصريفًا محكومًا بالتوصيلية ومخرجًا لضخ الكيماويات، تؤدي وحدة مدمجة الغرض وتبقى على تهيئتها.',
    },
    benefits: [
      { id: 'focus', icon: 'gauge', label: { en: 'Does one thing well', ar: 'تؤدي مهمة واحدة بإتقان' }, body: { en: 'A narrow feature set is easier to commission correctly and harder to misconfigure.', ar: 'مجموعة الوظائف المحدودة أسهل في التشغيل الصحيح وأصعب في الضبط الخاطئ.' } },
      { id: 'robust', icon: 'shield', label: { en: 'Plant-room robust', ar: 'متينة لظروف غرفة المعدات' }, body: { en: 'Built for the environment it is installed in rather than for a control room.', ar: 'مصممة للبيئة التي تُركّب فيها لا لغرفة تحكم.' } },
    ],
    applications: [
      { en: 'Boiler blowdown control', ar: 'التحكم في تصريف الغلايات' },
      { en: 'Cooling tower conductivity control', ar: 'التحكم في توصيلية أبراج التبريد' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'Walchem W100 series', ar: 'سلسلة Walchem W100' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Conductivity controller', ar: 'وحدة تحكم بالتوصيلية' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'W100W datasheet', 'ورقة بيانات W100W', 'datasheet')],
    solutions: ['boiler-steam', 'cooling-water'],
    industries: ['manufacturing', 'commercial-buildings', 'food-beverage', 'hospitality'],
    relatedProducts: ['walchem-intuition-6', 'walchem-conductivity-sensors', 'walchem-e-series'],
  },

  /* ================= WALCHEM — SENSORS ================================== */
  {
    slug: 'walchem-ph-orp-sensors',
    status: 'published',
    name: 'Walchem pH & ORP Electrodes',
    partner: 'walchem',
    category: 'sensors',
    technology: 'sensors-measurement',
    title: { en: 'pH & ORP Electrodes', ar: 'أقطاب pH وORP' },
    positioning: { en: 'The two measurements that set the behaviour of most treatment chemistry.', ar: 'القياسان اللذان يحددان سلوك معظم كيمياء المعالجة.' },
    summary: { en: 'pH and ORP electrodes across differential, standard and high-temperature constructions.', ar: 'أقطاب pH وORP بتكوينات تفاضلية وقياسية وعالية الحرارة.' },
    metaTitle: { en: 'Walchem pH & ORP Electrodes | C-Water', ar: 'أقطاب pH وORP من Walchem | C-Water' },
    metaDescription: { en: 'Walchem pH and ORP electrodes for industrial water treatment, including differential and high-temperature constructions, selected and calibrated by C-Water.', ar: 'أقطاب pH وORP من Walchem لمعالجة المياه الصناعية، بما فيها التكوينات التفاضلية وعالية الحرارة، تختارها وتعايرها C-Water.' },
    overview: {
      en: 'pH governs inhibitor performance, scaling tendency and biocide effectiveness; ORP indicates whether the water is currently in an oxidising state. Both are only as good as the electrode’s installation and calibration discipline.',
      ar: 'تحكم درجة الحموضة أداء المثبطات وميل الترسب وفعالية المبيدات، ويشير ORP إلى ما إذا كانت المياه في حالة مؤكسِدة حاليًا. وكلاهما لا يفوق جودة تركيب القطب وانضباط معايرته.',
    },
    benefits: [
      { id: 'range', icon: 'sensor', label: { en: 'Construction matched to duty', ar: 'تكوين يناسب المهمة' }, body: { en: 'Differential constructions for fouling or high-conductivity duty; high-temperature bodies where process conditions demand.', ar: 'تكوينات تفاضلية للتطبيقات المعرضة للاتساخ أو عالية التوصيلية، وأجسام عالية الحرارة حيث تتطلب ظروف العملية ذلك.' } },
      { id: 'life', icon: 'shield', label: { en: 'Predictable service life', ar: 'عمر خدمة متوقع' }, body: { en: 'An electrode selected for the actual chemistry lasts longer and drifts less between calibrations.', ar: 'القطب المختار وفق الكيمياء الفعلية يدوم أطول وينحرف أقل بين المعايرات.' } },
    ],
    applications: [
      { en: 'Cooling water pH control', ar: 'التحكم في حموضة مياه التبريد' },
      { en: 'Halogen feed control by ORP', ar: 'التحكم في ضخ الهالوجينات عبر ORP' },
      { en: 'Effluent neutralisation', ar: 'تعادل المخلفات السائلة' },
      { en: 'Process water monitoring', ar: 'مراقبة مياه العمليات' },
    ],
    specs: [
      { key: { en: 'Measurement', ar: 'القياس' }, value: { en: 'pH and ORP', ar: 'pH وORP' } },
      { key: { en: 'Constructions published by Walchem', ar: 'التكوينات المنشورة من Walchem' }, value: { en: 'WDS differential, WEL, high-temperature', ar: 'WDS التفاضلي، WEL، عالي الحرارة' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'pH and ORP electrode selection guide', 'دليل اختيار أقطاب pH وORP', 'technical-guide')],
    solutions: ['cooling-water', 'wastewater', 'process-water', 'potable-water'],
    industries: ['manufacturing', 'chemical-petrochemical', 'food-beverage', 'power-utilities'],
    relatedProducts: ['walchem-intuition-9', 'walchem-conductivity-sensors', 'walchem-disinfection-sensors'],
  },

  {
    slug: 'walchem-conductivity-sensors',
    status: 'published',
    name: 'Walchem Conductivity Sensors',
    partner: 'walchem',
    category: 'sensors',
    technology: 'sensors-measurement',
    title: { en: 'Conductivity Sensors', ar: 'مستشعرات التوصيلية' },
    positioning: { en: 'The practical basis for controlling cycles of concentration and blowdown.', ar: 'الأساس العملي للتحكم في دورات التركيز والتصريف.' },
    summary: { en: 'Contacting and electrodeless conductivity measurement for cooling, boiler and RO duty.', ar: 'قياس التوصيلية بالتلامس وبدون تلامس لتطبيقات التبريد والغلايات والتناضح العكسي.' },
    metaTitle: { en: 'Walchem Conductivity Sensors | C-Water', ar: 'مستشعرات التوصيلية من Walchem | C-Water' },
    metaDescription: { en: 'Walchem contacting and electrodeless conductivity sensors for cooling tower cycles control, boiler blowdown and RO monitoring.', ar: 'مستشعرات التوصيلية بالتلامس وبدون تلامس من Walchem للتحكم في دورات أبراج التبريد وتصريف الغلايات ومراقبة التناضح العكسي.' },
    overview: {
      en: 'Conductivity stands in for dissolved solids concentration, which makes it the measurement most water systems are actually controlled on. Contacting cells suit clean water; electrodeless sensors tolerate fouling and wider ranges.',
      ar: 'تنوب التوصيلية عن تركيز المواد الصلبة الذائبة، مما يجعلها القياس الذي تُدار عليه معظم أنظمة المياه فعليًا. تناسب الخلايا التلامسية المياه النظيفة، بينما تتحمل المستشعرات غير التلامسية الاتساخ والنطاقات الأوسع.',
    },
    benefits: [
      { id: 'type', icon: 'sensor', label: { en: 'Right sensing principle', ar: 'مبدأ استشعار مناسب' }, body: { en: 'Electrodeless where fouling would compromise a contacting cell; contacting where low-range accuracy matters.', ar: 'غير تلامسي حيث يفسد الاتساخ خلية تلامسية، وتلامسي حيث تهم الدقة في النطاقات المنخفضة.' } },
      { id: 'control', icon: 'controller', label: { en: 'Direct control input', ar: 'مدخل تحكم مباشر' }, body: { en: 'Drives blowdown and chemical feed so cycles are held at a measured value rather than a fixed schedule.', ar: 'يقود التصريف وضخ الكيماويات لتُثبَّت دورات التركيز عند قيمة مقاسة لا وفق جدول ثابت.' } },
    ],
    applications: [
      { en: 'Cooling tower cycles of concentration', ar: 'دورات التركيز في أبراج التبريد' },
      { en: 'Boiler blowdown control', ar: 'التحكم في تصريف الغلايات' },
      { en: 'RO feed and permeate monitoring', ar: 'مراقبة تغذية ونفاذ التناضح العكسي' },
    ],
    specs: [
      { key: { en: 'Measurement', ar: 'القياس' }, value: { en: 'Electrical conductivity', ar: 'التوصيلية الكهربائية' } },
      { key: { en: 'Sensing principles published by Walchem', ar: 'مبادئ الاستشعار المنشورة من Walchem' }, value: { en: 'Contacting and electrodeless', ar: 'تلامسي وغير تلامسي' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Conductivity sensor selection guide', 'دليل اختيار مستشعرات التوصيلية', 'technical-guide')],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'process-water'],
    industries: ['manufacturing', 'power-utilities', 'food-beverage', 'healthcare', 'pharmaceutical-cosmetics'],
    relatedProducts: ['walchem-intuition-9', 'walchem-w100', 'walchem-ph-orp-sensors'],
  },

  {
    slug: 'walchem-disinfection-sensors',
    status: 'published',
    name: 'Walchem Disinfection Sensors',
    partner: 'walchem',
    category: 'sensors',
    technology: 'sensors-measurement',
    title: { en: 'Disinfection Sensors', ar: 'مستشعرات التطهير' },
    positioning: { en: 'Measuring the disinfectant that is actually present, not the dose that was set.', ar: 'قياس المطهر الموجود فعلًا، لا الجرعة التي ضُبطت.' },
    summary: { en: 'Online disinfection measurement for potable, process and recreational water duty.', ar: 'قياس متصل للتطهير في مياه الشرب والعمليات والمياه الترفيهية.' },
    metaTitle: { en: 'Walchem Disinfection Sensors | C-Water', ar: 'مستشعرات التطهير من Walchem | C-Water' },
    metaDescription: { en: 'Walchem disinfection sensors for continuous residual measurement in potable water, process water and pool systems.', ar: 'مستشعرات التطهير من Walchem للقياس المستمر للمتبقي في مياه الشرب ومياه العمليات وأنظمة المسابح.' },
    overview: {
      en: 'Residual decays with time, temperature and demand. A correct dose at the plant does not guarantee a correct residual at the far point of a network — which is where the measurement belongs.',
      ar: 'يتحلل المتبقي مع الزمن ودرجة الحرارة والطلب. فالجرعة الصحيحة عند المحطة لا تضمن متبقيًا صحيحًا عند أبعد نقطة في الشبكة — وهناك ينبغي أن يكون القياس.',
    },
    benefits: [
      { id: 'residual', icon: 'sensor', label: { en: 'Measures the outcome', ar: 'يقيس النتيجة' }, body: { en: 'Controls on what is present in the water rather than on what was fed into it.', ar: 'يتحكم بناءً على ما هو موجود في المياه لا على ما ضُخّ فيها.' } },
      { id: 'record', icon: 'clipboard', label: { en: 'Continuous evidence', ar: 'دليل مستمر' }, body: { en: 'Logged residual provides the record that periodic sampling cannot.', ar: 'يوفر المتبقي المسجَّل السجل الذي لا توفره العينات الدورية.' } },
    ],
    applications: [
      { en: 'Potable water residual control', ar: 'التحكم في متبقي مياه الشرب' },
      { en: 'Cooling water halogen control', ar: 'التحكم في هالوجينات مياه التبريد' },
      { en: 'Pool and recreational water', ar: 'مياه المسابح والترفيه' },
    ],
    specs: [
      { key: { en: 'Measurement', ar: 'القياس' }, value: { en: 'Disinfectant residual', ar: 'متبقي المطهر' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Online amperometric sensing', ar: 'استشعار أمبيرومتري متصل' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Disinfection sensor datasheet', 'ورقة بيانات مستشعر التطهير', 'datasheet')],
    solutions: ['potable-water', 'cooling-water', 'process-water'],
    industries: ['hospitality', 'healthcare', 'food-beverage', 'government-municipal', 'commercial-buildings'],
    relatedProducts: ['walchem-intuition-6', 'walchem-ph-orp-sensors', 'walchem-ix-series'],
  },

  /* ================= WALCHEM — PUMPS ==================================== */
  {
    slug: 'walchem-ix-series',
    status: 'published',
    name: 'Walchem IX Series',
    partner: 'walchem',
    category: 'metering-pumps',
    technology: 'chemical-dosing',
    title: { en: 'IX Series Metering Pumps', ar: 'مضخات الجرعات سلسلة IX' },
    positioning: { en: 'Electronic metering pumps for treatment programmes that need real turndown.', ar: 'مضخات جرعات إلكترونية لبرامج المعالجة التي تحتاج نطاق تعديل حقيقيًا.' },
    summary: { en: 'Walchem’s electronic metering pump platform for controlled chemical delivery.', ar: 'منصة مضخات الجرعات الإلكترونية من Walchem للضخ الكيميائي المحكوم.' },
    metaTitle: { en: 'Walchem IX Series Metering Pumps | C-Water', ar: 'مضخات الجرعات Walchem سلسلة IX | C-Water' },
    metaDescription: { en: 'Walchem IX Series electronic metering pumps for water treatment chemical dosing, sized and commissioned by C-Water against the treatment programme.', ar: 'مضخات الجرعات الإلكترونية Walchem سلسلة IX لضخ كيماويات معالجة المياه، تحجّمها وتشغّلها C-Water وفق برنامج المعالجة.' },
    overview: {
      en: 'A metering pump is chosen for the turndown a programme needs, not for its maximum output. C-Water sizes against the actual dose range, viscosity, back pressure and duty cycle before capacity is considered.',
      ar: 'تُختار مضخة الجرعات وفق نطاق التعديل الذي يحتاجه البرنامج، لا وفق أقصى إنتاجية لها. وتحجّمها C-Water وفق نطاق الجرعة الفعلي واللزوجة والضغط المعاكس ودورة التشغيل قبل النظر في السعة.',
    },
    benefits: [
      { id: 'turndown', icon: 'pump', label: { en: 'Usable turndown', ar: 'نطاق تعديل قابل للاستخدام' }, body: { en: 'A programme that varies with load needs a pump that can follow it at the low end as well as the high.', ar: 'البرنامج الذي يتغير مع الحمل يحتاج مضخة تتبعه في الطرف المنخفض كما في المرتفع.' } },
      { id: 'control', icon: 'controller', label: { en: 'Controller-driven', ar: 'مُدارة بوحدة تحكم' }, body: { en: 'Accepts control signals so dosing follows a measured parameter rather than a timer.', ar: 'تقبل إشارات التحكم لتتبع الجرعات متغيرًا مقاسًا بدل المؤقت.' } },
    ],
    applications: [
      { en: 'Cooling tower inhibitor and biocide feed', ar: 'ضخ المثبطات والمبيدات لأبراج التبريد' },
      { en: 'Boiler chemical feed', ar: 'ضخ كيماويات الغلايات' },
      { en: 'Effluent coagulant and polymer dosing', ar: 'ضخ المروّبات والبوليمرات للمخلفات' },
      { en: 'pH correction', ar: 'تصحيح الحموضة' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'Walchem IX Series', ar: 'Walchem سلسلة IX' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Electronic metering pump', ar: 'مضخة جرعات إلكترونية' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'IX Series datasheet', 'ورقة بيانات سلسلة IX', 'datasheet')],
    solutions: ['cooling-water', 'boiler-steam', 'wastewater', 'ro-membranes'],
    industries: ['manufacturing', 'chemical-petrochemical', 'oil-gas', 'food-beverage'],
    relatedProducts: ['walchem-e-series', 'walchem-lk-series', 'walchem-intuition-9'],
  },

  {
    slug: 'walchem-e-series',
    status: 'published',
    name: 'Walchem E-Series',
    partner: 'walchem',
    category: 'metering-pumps',
    technology: 'chemical-dosing',
    title: { en: 'E-Series Metering Pumps', ar: 'مضخات الجرعات سلسلة E' },
    positioning: { en: 'Solenoid-driven metering across general and high-viscosity duty.', ar: 'ضخ جرعات بمحرك سولينويد للتطبيقات العامة وعالية اللزوجة.' },
    summary: { en: 'The E-Series covers standard chemical feed and, in the EH variant, high-viscosity applications.', ar: 'تغطي سلسلة E ضخ الكيماويات القياسي، وفي الإصدار EH التطبيقات عالية اللزوجة.' },
    metaTitle: { en: 'Walchem E-Series Metering Pumps | C-Water', ar: 'مضخات الجرعات Walchem سلسلة E | C-Water' },
    metaDescription: { en: 'Walchem E-Series metering pumps including EWN, EWP and EHE variants for water treatment chemical dosing across standard and high-viscosity duty.', ar: 'مضخات الجرعات Walchem سلسلة E بإصداراتها EWN وEWP وEHE لضخ كيماويات معالجة المياه في التطبيقات القياسية وعالية اللزوجة.' },
    overview: {
      en: 'Viscosity, degassing behaviour and back pressure narrow a pump selection long before capacity does. The E-Series range exists because those constraints differ so widely between treatment chemicals.',
      ar: 'تضيّق اللزوجة وسلوك تحرر الغازات والضغط المعاكس اختيارَ المضخة قبل السعة بكثير. ووجود مدى سلسلة E سببه أن هذه القيود تتفاوت بشدة بين كيماويات المعالجة.',
    },
    benefits: [
      { id: 'viscosity', icon: 'flask', label: { en: 'Handles difficult chemistry', ar: 'تتعامل مع كيمياء صعبة' }, body: { en: 'High-viscosity variants exist for the chemicals a standard pump will not feed reliably.', ar: 'توجد إصدارات عالية اللزوجة للكيماويات التي لا تضخها مضخة قياسية بموثوقية.' } },
      { id: 'range', icon: 'pump', label: { en: 'A variant per duty', ar: 'إصدار لكل مهمة' }, body: { en: 'EWN, EWP and EHE constructions published by Walchem cover different chemical and pressure conditions.', ar: 'تغطي تكوينات EWN وEWP وEHE المنشورة من Walchem ظروفًا كيميائية وضغطية مختلفة.' } },
    ],
    applications: [
      { en: 'General water treatment chemical feed', ar: 'ضخ كيماويات معالجة المياه العامة' },
      { en: 'Antiscalant injection', ar: 'حقن مانع الترسب' },
      { en: 'High-viscosity polymer dosing', ar: 'ضخ البوليمرات عالية اللزوجة' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'Walchem E-Series', ar: 'Walchem سلسلة E' } },
      { key: { en: 'Variants published by Walchem', ar: 'الإصدارات المنشورة من Walchem' }, value: { en: 'EWN, EWP, EHE and EH high-viscosity', ar: 'EWN، EWP، EHE، وEH عالية اللزوجة' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'E-Series datasheet', 'ورقة بيانات سلسلة E', 'datasheet')],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'wastewater'],
    industries: ['manufacturing', 'food-beverage', 'agriculture-irrigation', 'chemical-petrochemical'],
    relatedProducts: ['walchem-ix-series', 'walchem-lk-series', 'walchem-w100'],
  },

  {
    slug: 'walchem-lk-series',
    status: 'published',
    name: 'Walchem LK / LKN Series',
    partner: 'walchem',
    category: 'metering-pumps',
    technology: 'chemical-dosing',
    title: { en: 'LK & LKN Series Metering Pumps', ar: 'مضخات الجرعات سلسلتا LK وLKN' },
    positioning: { en: 'Motor-driven metering for continuous, higher-capacity chemical feed.', ar: 'ضخ جرعات بمحرك للتغذية الكيميائية المستمرة عالية السعة.' },
    summary: { en: 'Motor-driven metering pumps for duties beyond the range of solenoid units.', ar: 'مضخات جرعات بمحرك لتطبيقات تتجاوز مدى وحدات السولينويد.' },
    metaTitle: { en: 'Walchem LK & LKN Series Metering Pumps | C-Water', ar: 'مضخات الجرعات Walchem سلسلتا LK وLKN | C-Water' },
    metaDescription: { en: 'Walchem LK and LKN Series motor-driven metering pumps for continuous higher-capacity chemical dosing in industrial water treatment.', ar: 'مضخات الجرعات Walchem سلسلتا LK وLKN المُدارتان بمحرك للضخ الكيميائي المستمر عالي السعة في معالجة المياه الصناعية.' },
    overview: {
      en: 'Where feed is continuous and the required volume is beyond a solenoid pump’s comfortable range, a motor-driven unit gives steadier delivery and a longer service interval.',
      ar: 'حيث يكون الضخ مستمرًا والحجم المطلوب يتجاوز النطاق المريح لمضخة سولينويد، تمنح الوحدة المُدارة بمحرك ضخًا أكثر ثباتًا وفترة خدمة أطول.',
    },
    benefits: [
      { id: 'continuous', icon: 'pump', label: { en: 'Steady continuous feed', ar: 'ضخ مستمر ثابت' }, body: { en: 'Suited to programmes where the chemical is fed constantly rather than in response to an event.', ar: 'تناسب البرامج التي يُضخ فيها الكيماوي باستمرار لا استجابةً لحدث.' } },
      { id: 'capacity', icon: 'flow', label: { en: 'Higher capacity range', ar: 'نطاق سعة أعلى' }, body: { en: 'Covers duties above what solenoid metering handles comfortably.', ar: 'تغطي أحمالًا تفوق ما تتحمله مضخات السولينويد براحة.' } },
    ],
    applications: [
      { en: 'Continuous inhibitor feed', ar: 'ضخ المثبطات المستمر' },
      { en: 'Large-system chemical dosing', ar: 'ضخ كيماويات الأنظمة الكبيرة' },
      { en: 'Effluent treatment chemical feed', ar: 'ضخ كيماويات معالجة المخلفات' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'Walchem LK / LKN Series', ar: 'Walchem سلسلتا LK / LKN' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Motor-driven metering pump', ar: 'مضخة جرعات مُدارة بمحرك' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'LK / LKN Series datasheet', 'ورقة بيانات سلسلتي LK / LKN', 'datasheet')],
    solutions: ['cooling-water', 'wastewater', 'industrial-water'],
    industries: ['power-utilities', 'chemical-petrochemical', 'oil-gas', 'manufacturing'],
    relatedProducts: ['walchem-ix-series', 'walchem-e-series'],
  },

  /* ================= WALCHEM — SOFTWARE ================================= */
  {
    slug: 'walchem-fluent',
    status: 'published',
    name: 'Walchem Fluent',
    partner: 'walchem',
    category: 'software',
    technology: 'automation-remote-monitoring',
    title: { en: 'Walchem Fluent Monitoring Platform', ar: 'منصة المراقبة Walchem Fluent' },
    positioning: { en: 'Controller data available away from the plant room.', ar: 'بيانات وحدات التحكم متاحة خارج غرفة المعدات.' },
    summary: { en: 'Walchem’s cloud platform for remote visibility of connected controller data.', ar: 'المنصة السحابية من Walchem للرؤية عن بُعد لبيانات وحدات التحكم المتصلة.' },
    metaTitle: { en: 'Walchem Fluent Remote Water Management | C-Water', ar: 'الإدارة عن بُعد للمياه عبر Walchem Fluent | C-Water' },
    metaDescription: { en: 'Walchem Fluent cloud water management platform for remote monitoring of controller data, trends and alarms, applied within C-Water monitoring and reporting services.', ar: 'منصة إدارة المياه السحابية Walchem Fluent للمراقبة عن بُعد لبيانات وحدات التحكم والاتجاهات والإنذارات، ضمن خدمات المراقبة والتقارير لدى C-Water.' },
    overview: {
      en: 'Fluent is where connected controller data becomes visible outside the plant. Its value to a C-Water customer is that a treatment specialist can look at a trend before a site visit rather than after a problem.',
      ar: 'Fluent هي حيث تصبح بيانات وحدات التحكم المتصلة مرئية خارج المنشأة. وقيمتها لعميل C-Water أن يستطيع متخصص المعالجة الاطلاع على اتجاه ما قبل زيارة الموقع لا بعد وقوع مشكلة.',
    },
    benefits: [
      { id: 'visibility', icon: 'monitor', label: { en: 'Visibility between visits', ar: 'رؤية بين الزيارات' }, body: { en: 'The gap between service visits is where most damaging conditions develop unobserved.', ar: 'الفجوة بين زيارات الخدمة هي حيث تنشأ معظم الحالات الضارة دون ملاحظة.' } },
      { id: 'alarm', icon: 'gauge', label: { en: 'Conditions pushed out', ar: 'إرسال الحالات فور وقوعها' }, body: { en: 'An alarm reaches someone rather than waiting on a display nobody is reading.', ar: 'يصل الإنذار إلى شخص بدل انتظاره على شاشة لا يقرأها أحد.' } },
      { id: 'history', icon: 'optimize', label: { en: 'History for review', ar: 'سجل للمراجعة' }, body: { en: 'Trends across weeks and seasons support the periodic technical review.', ar: 'تدعم الاتجاهات عبر الأسابيع والفصول المراجعة الفنية الدورية.' } },
    ],
    applications: [
      { en: 'Multi-site facility management', ar: 'إدارة منشآت متعددة المواقع' },
      { en: 'Remote or unattended plant', ar: 'المنشآت النائية أو غير المأهولة' },
      { en: 'Treatment programme reporting', ar: 'تقارير برامج المعالجة' },
    ],
    specs: [
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Cloud water management platform', ar: 'منصة سحابية لإدارة المياه' } },
      { key: { en: 'Data source', ar: 'مصدر البيانات' }, value: { en: 'Connected Walchem controllers', ar: 'وحدات تحكم Walchem المتصلة' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('br', 'Walchem Fluent overview', 'نظرة عامة على Walchem Fluent', 'brochure')],
    solutions: ['cooling-water', 'boiler-steam', 'industrial-water'],
    industries: ['manufacturing', 'commercial-buildings', 'hospitality', 'oil-gas', 'government-municipal'],
    relatedProducts: ['walchem-intuition-9', 'walchem-intuition-6'],
  },

  /* ================= TIMEX — FILTRATION ================================= */
  {
    slug: 'timex-kmf-series',
    status: 'published',
    name: 'TIMEX KMF Series',
    partner: 'timex',
    category: 'self-cleaning-filters',
    technology: 'filtration',
    title: { en: 'KMF Series Self-Cleaning Filters', ar: 'مرشحات KMF ذاتية التنظيف' },
    positioning: { en: 'Automatic screen filtration for continuous duty on heavy solids load.', ar: 'ترشيح شبكي أوتوماتيكي للتشغيل المستمر تحت أحمال صلبة ثقيلة.' },
    summary: { en: 'Self-cleaning screen filters that clear the element without interrupting the main flow.', ar: 'مرشحات شبكية ذاتية التنظيف تنظّف العنصر دون قطع التدفق الرئيسي.' },
    metaTitle: { en: 'TIMEX KMF Series Self-Cleaning Filters | C-Water', ar: 'مرشحات TIMEX KMF ذاتية التنظيف | C-Water' },
    metaDescription: { en: 'TIMEX KMF Series automatic self-cleaning filters for industrial water, cooling tower side-stream, irrigation and produced water duty, sized by C-Water to measured solids load.', ar: 'مرشحات TIMEX سلسلة KMF الأوتوماتيكية ذاتية التنظيف للمياه الصناعية والتيار الجانبي لأبراج التبريد والري ومياه الإنتاج، تحجّمها C-Water وفق حمل المواد الصلبة المقاس.' },
    overview: {
      en: 'A self-cleaning filter earns its cost where manual element cleaning would otherwise be frequent. C-Water sizes to the measured solids load, its nature and the available differential pressure — not to nominal pipe diameter.',
      ar: 'يستحق المرشح ذاتي التنظيف تكلفته حيث يكون تنظيف العنصر يدويًا متكررًا. وتحجّمه C-Water وفق حمل المواد الصلبة المقاس وطبيعته وفرق الضغط المتاح — لا وفق قطر الخط الاسمي.',
    },
    benefits: [
      { id: 'continuous', icon: 'recycle', label: { en: 'Cleans without stopping flow', ar: 'ينظّف دون إيقاف التدفق' }, body: { en: 'Suited to systems that cannot be taken offline to service a filter element.', ar: 'يناسب الأنظمة التي لا يمكن إيقافها لخدمة عنصر ترشيح.' } },
      { id: 'labour', icon: 'wrench', label: { en: 'Removes a manual task', ar: 'يلغي مهمة يدوية' }, body: { en: 'Where manual cleaning is frequent, automation is usually justified on labour alone.', ar: 'حيث يتكرر التنظيف اليدوي، تُبرَّر الأتمتة عادةً بتوفير العمالة وحده.' } },
      { id: 'signal', icon: 'gauge', label: { en: 'Cleaning frequency as data', ar: 'تكرار التنظيف كبيانات' }, body: { en: 'How often the filter cleans is a direct readout of what is arriving in the water.', ar: 'تكرار تنظيف المرشح قراءة مباشرة لما يصل مع المياه.' } },
    ],
    applications: [
      { en: 'Cooling tower side-stream filtration', ar: 'الترشيح الجانبي لأبراج التبريد' },
      { en: 'Irrigation network protection', ar: 'حماية شبكات الري' },
      { en: 'Process and produced water', ar: 'مياه العمليات والإنتاج' },
      { en: 'RO pretreatment', ar: 'المعالجة الأولية للتناضح العكسي' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'TIMEX KMF Series', ar: 'TIMEX سلسلة KMF' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Automatic self-cleaning screen filter', ar: 'مرشح شبكي أوتوماتيكي ذاتي التنظيف' } },
      { key: { en: 'Cleaning trigger', ar: 'مُطلِق التنظيف' }, value: { en: 'Differential pressure, elapsed time or manual command', ar: 'فرق الضغط أو الزمن المنقضي أو أمر يدوي' } },
    ],
    specsPendingReview: true,
    documents: [
      onRequestDoc('ds', 'KMF Series datasheet', 'ورقة بيانات سلسلة KMF', 'datasheet'),
      onRequestDoc('cat', 'TIMEX filtration catalogue', 'كتالوج ترشيح TIMEX', 'catalogue'),
    ],
    solutions: ['cooling-water', 'ro-membranes', 'industrial-water', 'wastewater', 'process-water'],
    industries: ['manufacturing', 'oil-gas', 'power-utilities', 'agriculture-irrigation', 'government-municipal', 'aquaculture'],
    relatedProducts: ['timex-svf-series', 'timex-hydrospin', 'timex-disc-filter', 'timex-separator-filter'],
  },

  {
    slug: 'timex-svf-series',
    status: 'published',
    name: 'TIMEX SVF Series',
    partner: 'timex',
    category: 'self-cleaning-filters',
    technology: 'filtration',
    title: { en: 'SVF Series Self-Cleaning Filters', ar: 'مرشحات SVF ذاتية التنظيف' },
    positioning: { en: 'Automatic screen filtration for side-stream and protective duty.', ar: 'ترشيح شبكي أوتوماتيكي للتيار الجانبي والحماية.' },
    summary: { en: 'Self-cleaning filtration configured for continuous protective service.', ar: 'ترشيح ذاتي التنظيف مُهيّأ للخدمة الحمائية المستمرة.' },
    metaTitle: { en: 'TIMEX SVF Series Self-Cleaning Filters | C-Water', ar: 'مرشحات TIMEX SVF ذاتية التنظيف | C-Water' },
    metaDescription: { en: 'TIMEX SVF Series self-cleaning filters for cooling tower side-stream filtration and downstream equipment protection in industrial water systems.', ar: 'مرشحات TIMEX سلسلة SVF ذاتية التنظيف للترشيح الجانبي لأبراج التبريد وحماية المعدات اللاحقة في أنظمة المياه الصناعية.' },
    overview: {
      en: 'Side-stream filtration works by treating a fraction of a recirculating volume continuously. Over a cooling season it removes far more solids than its instantaneous flow rate suggests.',
      ar: 'يعمل الترشيح الجانبي بمعالجة جزء من الحجم الدائر بشكل مستمر. وعلى مدى موسم تبريد، يزيل مواد صلبة أكثر بكثير مما يوحي به معدل تدفقه اللحظي.',
    },
    benefits: [
      { id: 'side', icon: 'filter', label: { en: 'Economical side-stream duty', ar: 'ترشيح جانبي اقتصادي' }, body: { en: 'Treating a fraction of the volume continuously is usually cheaper than full-flow filtration.', ar: 'معالجة جزء من الحجم باستمرار أرخص عادةً من الترشيح الكلي.' } },
      { id: 'chemical', icon: 'flask', label: { en: 'Reduces chemical demand', ar: 'يقلل الطلب على الكيماويات' }, body: { en: 'Solids removed mechanically are solids the treatment programme no longer has to disperse.', ar: 'المواد الصلبة المزالة ميكانيكيًا لم يعد على برنامج المعالجة تشتيتها.' } },
    ],
    applications: [
      { en: 'Cooling tower basin filtration', ar: 'ترشيح أحواض أبراج التبريد' },
      { en: 'Heat exchanger protection', ar: 'حماية المبادلات الحرارية' },
      { en: 'RO pretreatment', ar: 'المعالجة الأولية للتناضح العكسي' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'TIMEX SVF Series', ar: 'TIMEX سلسلة SVF' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Automatic self-cleaning screen filter', ar: 'مرشح شبكي أوتوماتيكي ذاتي التنظيف' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'SVF Series datasheet', 'ورقة بيانات سلسلة SVF', 'datasheet')],
    solutions: ['cooling-water', 'ro-membranes', 'process-water', 'industrial-water'],
    industries: ['manufacturing', 'hospitality', 'commercial-buildings', 'power-utilities', 'food-beverage'],
    relatedProducts: ['timex-kmf-series', 'timex-hydrospin', 'timex-cartridge-filter'],
  },

  {
    slug: 'timex-hydrospin',
    status: 'published',
    name: 'TIMEX HydroSpin®',
    partner: 'timex',
    category: 'self-cleaning-filters',
    technology: 'filtration',
    title: { en: 'HydroSpin® Modular Self-Cleaning Filters', ar: 'مرشحات HydroSpin® النمطية ذاتية التنظيف' },
    positioning: { en: 'Modular self-cleaning filtration for installations that need to scale.', ar: 'ترشيح نمطي ذاتي التنظيف للتركيبات التي تحتاج قابلية للتوسع.' },
    summary: { en: 'A modular design approach to automatic filtration capacity.', ar: 'منهج تصميم نمطي لسعة الترشيح الأوتوماتيكي.' },
    metaTitle: { en: 'TIMEX HydroSpin® Self-Cleaning Filters | C-Water', ar: 'مرشحات TIMEX HydroSpin® ذاتية التنظيف | C-Water' },
    metaDescription: { en: 'TIMEX HydroSpin® modular self-cleaning filters for scalable automatic filtration capacity in industrial and municipal water systems.', ar: 'مرشحات TIMEX HydroSpin® النمطية ذاتية التنظيف لسعة ترشيح أوتوماتيكي قابلة للتوسع في أنظمة المياه الصناعية والبلدية.' },
    overview: {
      en: 'A modular arrangement allows capacity to be added without replacing the installation, and allows one module to be isolated for service while the rest continue.',
      ar: 'يتيح الترتيب النمطي إضافة سعة دون استبدال التركيب، ويسمح بعزل وحدة واحدة للخدمة بينما تواصل البقية العمل.',
    },
    benefits: [
      { id: 'scale', icon: 'network', label: { en: 'Capacity can grow', ar: 'سعة قابلة للنمو' }, body: { en: 'Useful where future load is uncertain or expected to increase.', ar: 'مفيد حيث يكون الحمل المستقبلي غير مؤكد أو متوقعًا أن يزداد.' } },
      { id: 'service', icon: 'wrench', label: { en: 'Service without shutdown', ar: 'خدمة دون إيقاف' }, body: { en: 'One module isolated while the rest of the installation stays in service.', ar: 'تُعزل وحدة واحدة بينما يبقى باقي التركيب في الخدمة.' } },
    ],
    applications: [
      { en: 'Large-flow industrial filtration', ar: 'الترشيح الصناعي عالي التدفق' },
      { en: 'Municipal water systems', ar: 'أنظمة المياه البلدية' },
      { en: 'Irrigation network filtration', ar: 'ترشيح شبكات الري' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'TIMEX HydroSpin®', ar: 'TIMEX HydroSpin®' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Modular automatic self-cleaning filter', ar: 'مرشح أوتوماتيكي نمطي ذاتي التنظيف' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'HydroSpin® datasheet', 'ورقة بيانات HydroSpin®', 'datasheet')],
    solutions: ['industrial-water', 'potable-water', 'process-water'],
    industries: ['government-municipal', 'manufacturing', 'agriculture-irrigation', 'power-utilities'],
    relatedProducts: ['timex-kmf-series', 'timex-svf-series'],
  },

  {
    slug: 'timex-disc-filter',
    status: 'published',
    name: 'TIMEX Disc Filters',
    partner: 'timex',
    category: 'disc-filters',
    technology: 'filtration',
    title: { en: 'Disc Filters', ar: 'مرشحات الأقراص' },
    positioning: { en: 'Depth-style disc filtration for organic and fibrous load.', ar: 'ترشيح بالأقراص بأسلوب عمقي للأحمال العضوية والليفية.' },
    summary: { en: 'Disc filtration where the load is organic, fibrous or otherwise difficult for a screen.', ar: 'ترشيح بالأقراص حيث يكون الحمل عضويًا أو ليفيًا أو صعبًا على الشاشة.' },
    metaTitle: { en: 'TIMEX Disc Filters | C-Water', ar: 'مرشحات الأقراص من TIMEX | C-Water' },
    metaDescription: { en: 'TIMEX disc filters for irrigation, aquaculture and industrial water where organic and fibrous load makes screen filtration less effective.', ar: 'مرشحات الأقراص من TIMEX للري والاستزراع المائي والمياه الصناعية حيث تجعل الأحمال العضوية والليفية الترشيحَ الشبكي أقل فعالية.' },
    overview: {
      en: 'Stacked grooved discs give a longer, more tortuous flow path than a flat screen, which is why disc filtration handles algae, fibre and deformable solids better in many source waters.',
      ar: 'تمنح الأقراص المحزّزة المكدّسة مسار تدفق أطول وأكثر تعرجًا من الشاشة المسطحة، ولهذا يتعامل الترشيح بالأقراص بشكل أفضل مع الطحالب والألياف والمواد الصلبة القابلة للتشوه في كثير من مصادر المياه.',
    },
    benefits: [
      { id: 'organic', icon: 'biology', label: { en: 'Suited to organic load', ar: 'يناسب الأحمال العضوية' }, body: { en: 'Algae and fibrous material that blind a flat screen are retained through the disc depth.', ar: 'تُحتجَز الطحالب والمواد الليفية التي تسد الشاشة المسطحة عبر عمق الأقراص.' } },
      { id: 'backwash', icon: 'recycle', label: { en: 'Automatic backwash', ar: 'غسيل عكسي أوتوماتيكي' }, body: { en: 'Discs separate and are flushed clear on the cleaning cycle.', ar: 'تنفصل الأقراص وتُغسل في دورة التنظيف.' } },
    ],
    applications: [
      { en: 'Irrigation filtration', ar: 'ترشيح مياه الري' },
      { en: 'Aquaculture intake and solids removal', ar: 'مآخذ الاستزراع المائي وإزالة المواد الصلبة' },
      { en: 'Surface water pretreatment', ar: 'المعالجة الأولية للمياه السطحية' },
    ],
    specs: [
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Automatic disc filter', ar: 'مرشح أقراص أوتوماتيكي' } },
      { key: { en: 'Cleaning', ar: 'التنظيف' }, value: { en: 'Automatic backwash cycle', ar: 'دورة غسيل عكسي أوتوماتيكية' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Disc filter datasheet', 'ورقة بيانات مرشح الأقراص', 'datasheet')],
    solutions: ['industrial-water', 'wastewater', 'process-water', 'potable-water'],
    industries: ['agriculture-irrigation', 'aquaculture', 'food-beverage', 'government-municipal'],
    relatedProducts: ['timex-kmf-series', 'timex-drum-filter', 'timex-separator-filter'],
  },

  {
    slug: 'timex-drum-filter',
    status: 'published',
    name: 'TIMEX Drum Filters',
    partner: 'timex',
    category: 'screens-strainers',
    technology: 'filtration',
    title: { en: 'Drum Filters', ar: 'مرشحات الأسطوانات' },
    positioning: { en: 'Continuous mechanical solids removal at low pressure.', ar: 'إزالة ميكانيكية مستمرة للمواد الصلبة عند ضغط منخفض.' },
    summary: { en: 'Rotating drum filtration for continuous removal of suspended solids from open flows.', ar: 'ترشيح بأسطوانة دوارة لإزالة المواد الصلبة العالقة باستمرار من التدفقات المفتوحة.' },
    metaTitle: { en: 'TIMEX Drum Filters | C-Water', ar: 'مرشحات الأسطوانات من TIMEX | C-Water' },
    metaDescription: { en: 'TIMEX drum filters for continuous solids removal in aquaculture, wastewater and municipal water treatment applications.', ar: 'مرشحات الأسطوانات من TIMEX لإزالة المواد الصلبة باستمرار في تطبيقات الاستزراع المائي ومياه الصرف ومعالجة المياه البلدية.' },
    overview: {
      en: 'Drum filters work on gravity flow rather than pressure, which makes them well suited to applications where a pressurised filter would be an unnecessary energy cost.',
      ar: 'تعمل مرشحات الأسطوانات بالجاذبية لا بالضغط، مما يجعلها مناسبة للتطبيقات التي يكون فيها المرشح المضغوط تكلفة طاقة غير ضرورية.',
    },
    benefits: [
      { id: 'continuous', icon: 'recycle', label: { en: 'Continuous operation', ar: 'تشغيل مستمر' }, body: { en: 'Solids are removed as the drum rotates, without a batch cleaning cycle.', ar: 'تُزال المواد الصلبة مع دوران الأسطوانة دون دورة تنظيف دفعية.' } },
      { id: 'lowpressure', icon: 'energy', label: { en: 'Low pressure duty', ar: 'تشغيل بضغط منخفض' }, body: { en: 'Suited to gravity flows where pressurised filtration would be an unnecessary energy cost.', ar: 'تناسب التدفقات بالجاذبية حيث يكون الترشيح المضغوط تكلفة طاقة غير ضرورية.' } },
    ],
    applications: [
      { en: 'Aquaculture solids removal', ar: 'إزالة المواد الصلبة في الاستزراع المائي' },
      { en: 'Wastewater pretreatment', ar: 'المعالجة الأولية لمياه الصرف' },
      { en: 'Municipal treatment duty', ar: 'تطبيقات المعالجة البلدية' },
    ],
    specs: [
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Rotating drum filter', ar: 'مرشح أسطواني دوّار' } },
      { key: { en: 'Flow regime', ar: 'نظام التدفق' }, value: { en: 'Gravity', ar: 'بالجاذبية' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Drum filter datasheet', 'ورقة بيانات مرشح الأسطوانة', 'datasheet')],
    solutions: ['wastewater', 'industrial-water', 'process-water'],
    industries: ['aquaculture', 'food-beverage', 'government-municipal', 'manufacturing'],
    relatedProducts: ['timex-disc-filter', 'timex-daf', 'timex-kmf-series'],
  },

  {
    slug: 'timex-separator-filter',
    status: 'published',
    name: 'TIMEX TMN–TMF Separator Filters',
    partner: 'timex',
    category: 'separators',
    technology: 'filtration',
    title: { en: 'TMN–TMF Separator Filters', ar: 'مرشحات الفصل TMN–TMF' },
    positioning: { en: 'Centrifugal separation for sand and dense solids, ahead of everything else.', ar: 'فصل طرد مركزي للرمال والمواد الصلبة الكثيفة، قبل كل ما عداه.' },
    summary: { en: 'Hydrocyclone separation for abrasive and settleable load.', ar: 'فصل هيدروسيكلوني للأحمال الكاشطة والقابلة للترسيب.' },
    metaTitle: { en: 'TIMEX TMN–TMF Separator Filters | C-Water', ar: 'مرشحات الفصل TIMEX TMN–TMF | C-Water' },
    metaDescription: { en: 'TIMEX TMN–TMF hydrocyclone separator filters for sand and dense solids removal ahead of pumps, screens and downstream treatment.', ar: 'مرشحات الفصل الهيدروسيكلونية TIMEX TMN–TMF لإزالة الرمال والمواد الصلبة الكثيفة قبل المضخات والشاشات والمعالجة اللاحقة.' },
    overview: {
      en: 'Sand from a well source damages pumps and valves as well as blocking emitters and blinding filter elements. A separator removes the dense fraction with no element to clean at all.',
      ar: 'يتلف الرمل القادم من مصدر بئري المضخاتِ والصمامات، إضافة إلى سد النقاطات وانسداد عناصر الترشيح. ويزيل الفاصل الجزءَ الكثيف دون وجود عنصر يحتاج تنظيفًا أصلًا.',
    },
    benefits: [
      { id: 'noelement', icon: 'shield', label: { en: 'No element to blind', ar: 'لا عنصر يمكن أن ينسد' }, body: { en: 'Separation is by density, so heavy load does not translate into cleaning frequency.', ar: 'يعتمد الفصل على الكثافة، فلا يتحول الحمل الثقيل إلى تكرار تنظيف.' } },
      { id: 'protect', icon: 'wrench', label: { en: 'Protects rotating equipment', ar: 'يحمي المعدات الدوارة' }, body: { en: 'Abrasive solids removed before they reach pumps and valves.', ar: 'تُزال المواد الصلبة الكاشطة قبل وصولها إلى المضخات والصمامات.' } },
    ],
    applications: [
      { en: 'Well water sand removal', ar: 'إزالة الرمال من مياه الآبار' },
      { en: 'Irrigation intake protection', ar: 'حماية مآخذ الري' },
      { en: 'Produced and injection water', ar: 'مياه الإنتاج والحقن' },
    ],
    specs: [
      { key: { en: 'Product family', ar: 'عائلة المنتج' }, value: { en: 'TIMEX TMN–TMF', ar: 'TIMEX TMN–TMF' } },
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Hydrocyclone separator filter', ar: 'مرشح فصل هيدروسيكلوني' } },
      { key: { en: 'Separation principle', ar: 'مبدأ الفصل' }, value: { en: 'Centrifugal, by particle density', ar: 'طرد مركزي وفق كثافة الجسيمات' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Separator filter datasheet', 'ورقة بيانات مرشح الفصل', 'datasheet')],
    solutions: ['industrial-water', 'process-water', 'wastewater'],
    industries: ['oil-gas', 'agriculture-irrigation', 'manufacturing', 'government-municipal'],
    relatedProducts: ['timex-kmf-series', 'timex-disc-filter', 'timex-daf'],
  },

  {
    slug: 'timex-cartridge-filter',
    status: 'published',
    name: 'TIMEX Cartridge Filters',
    partner: 'timex',
    category: 'cartridge-filters',
    technology: 'filtration',
    title: { en: 'Cartridge Filters', ar: 'مرشحات الخراطيش' },
    positioning: { en: 'The final barrier before something that cannot tolerate particles.', ar: 'الحاجز الأخير قبل ما لا يحتمل وجود جسيمات.' },
    summary: { en: 'Fine cartridge filtration as the last protective stage ahead of membranes and instruments.', ar: 'ترشيح دقيق بالخراطيش كمرحلة حماية أخيرة قبل الأغشية وأجهزة القياس.' },
    metaTitle: { en: 'TIMEX Cartridge Filters | C-Water', ar: 'مرشحات الخراطيش من TIMEX | C-Water' },
    metaDescription: { en: 'TIMEX cartridge filters for fine filtration ahead of RO membranes, instrumentation and product-contact process water.', ar: 'مرشحات الخراطيش من TIMEX للترشيح الدقيق قبل أغشية التناضح العكسي وأجهزة القياس ومياه العمليات الملامسة للمنتج.' },
    overview: {
      en: 'Cartridge filtration is a barrier, not a treatment stage. Element life is a direct measure of how well the upstream stages are doing their job — short life is a pretreatment message.',
      ar: 'الترشيح بالخراطيش حاجز لا مرحلة معالجة. وعمر العنصر مقياس مباشر لأداء المراحل السابقة — فقِصر العمر رسالة من المعالجة الأولية.',
    },
    benefits: [
      { id: 'barrier', icon: 'shield', label: { en: 'Defined protective barrier', ar: 'حاجز حماية محدد' }, body: { en: 'The last defined point at which a particle can be stopped before the membrane.', ar: 'آخر نقطة محددة يمكن عندها إيقاف جسيم قبل الغشاء.' } },
      { id: 'diagnostic', icon: 'gauge', label: { en: 'Element life as diagnosis', ar: 'عمر العنصر كتشخيص' }, body: { en: 'How long a cartridge lasts tells you what the upstream filtration is missing.', ar: 'مدة بقاء الخرطوشة تخبرك بما يفوت الترشيح السابق.' } },
    ],
    applications: [
      { en: 'RO pretreatment final barrier', ar: 'الحاجز الأخير قبل التناضح العكسي' },
      { en: 'Process water polishing', ar: 'التنقية النهائية لمياه العمليات' },
      { en: 'Instrument protection', ar: 'حماية أجهزة القياس' },
    ],
    specs: [
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Cartridge filter housing and elements', ar: 'أوعية وعناصر مرشحات خراطيش' } },
      { key: { en: 'Position in train', ar: 'الموضع في سلسلة المعالجة' }, value: { en: 'Final barrier ahead of sensitive equipment', ar: 'حاجز أخير قبل المعدات الحساسة' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'Cartridge filter datasheet', 'ورقة بيانات مرشح الخراطيش', 'datasheet')],
    solutions: ['ro-membranes', 'process-water', 'potable-water'],
    industries: ['pharmaceutical-cosmetics', 'healthcare', 'food-beverage', 'manufacturing'],
    relatedProducts: ['timex-svf-series', 'timex-kmf-series', 'kurita-kuriverter-ik110'],
  },

  {
    slug: 'timex-daf',
    status: 'published',
    name: 'TIMEX Dissolved Air Flotation',
    partner: 'timex',
    category: 'flotation',
    technology: 'filtration',
    title: { en: 'Dissolved Air Flotation Systems', ar: 'أنظمة التعويم بالهواء المذاب' },
    positioning: { en: 'Removing what will not settle — oil, fat and low-density solids.', ar: 'إزالة ما لا يترسب — الزيوت والدهون والمواد الصلبة منخفضة الكثافة.' },
    summary: { en: 'DAF systems for separating oil, fat and buoyant solids from effluent streams.', ar: 'أنظمة تعويم بالهواء المذاب لفصل الزيوت والدهون والمواد الصلبة الطافية من تيارات المخلفات.' },
    metaTitle: { en: 'TIMEX Dissolved Air Flotation (DAF) | C-Water', ar: 'التعويم بالهواء المذاب DAF من TIMEX | C-Water' },
    metaDescription: { en: 'TIMEX dissolved air flotation systems for oil, fat and low-density solids removal in food, chemical and industrial effluent treatment.', ar: 'أنظمة التعويم بالهواء المذاب من TIMEX لإزالة الزيوت والدهون والمواد الصلبة منخفضة الكثافة في معالجة مخلفات الأغذية والكيماويات والصناعة.' },
    overview: {
      en: 'Gravity separation only works on solids denser than water. DAF attaches fine bubbles to the rest and floats them, which is what makes it the standard answer for fat, oil and light organic load.',
      ar: 'يعمل الفصل بالجاذبية على المواد الصلبة الأكثف من الماء فقط. أما التعويم بالهواء المذاب فيلصق فقاعات دقيقة بالبقية ويطفوها، وهذا ما يجعله الحل المعتاد للدهون والزيوت والأحمال العضوية الخفيفة.',
    },
    benefits: [
      { id: 'buoyant', icon: 'recycle', label: { en: 'Removes what will not settle', ar: 'يزيل ما لا يترسب' }, body: { en: 'Fat, oil and light organic solids that a settlement stage will pass straight through.', ar: 'الدهون والزيوت والمواد العضوية الخفيفة التي تمر مباشرة عبر مرحلة الترسيب.' } },
      { id: 'load', icon: 'energy', label: { en: 'Reduces downstream load', ar: 'يقلل الحمل على المراحل اللاحقة' }, body: { en: 'Removing load mechanically is cheaper than treating it chemically further down the train.', ar: 'إزالة الحمل ميكانيكيًا أرخص من معالجته كيميائيًا في مرحلة لاحقة.' } },
    ],
    applications: [
      { en: 'Food and beverage effluent', ar: 'مخلفات الأغذية والمشروبات' },
      { en: 'Oil-bearing industrial effluent', ar: 'المخلفات الصناعية الحاملة للزيوت' },
      { en: 'Produced water treatment', ar: 'معالجة مياه الإنتاج' },
    ],
    specs: [
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Dissolved air flotation system', ar: 'نظام تعويم بالهواء المذاب' } },
      { key: { en: 'Separation principle', ar: 'مبدأ الفصل' }, value: { en: 'Micro-bubble flotation of low-density solids', ar: 'تعويم المواد الصلبة منخفضة الكثافة بفقاعات دقيقة' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('ds', 'DAF system datasheet', 'ورقة بيانات نظام DAF', 'datasheet')],
    solutions: ['wastewater', 'industrial-water'],
    industries: ['food-beverage', 'oil-gas', 'chemical-petrochemical', 'manufacturing', 'government-municipal'],
    relatedProducts: ['timex-drum-filter', 'timex-separator-filter', 'walchem-ix-series'],
  },

  {
    slug: 'timex-treatment-systems',
    status: 'published',
    name: 'TIMEX Water Treatment Systems',
    partner: 'timex',
    category: 'treatment-systems',
    technology: 'engineering-integration',
    title: { en: 'Packaged Water Treatment Systems', ar: 'أنظمة معالجة المياه المجمّعة' },
    positioning: { en: 'Engineered treatment packages built around a defined duty.', ar: 'حزم معالجة مُهندَسة مبنية حول مهمة محددة.' },
    summary: { en: 'Packaged systems for potable, wastewater, recovery and irrigation duty.', ar: 'أنظمة مجمّعة لمياه الشرب ومياه الصرف والاستعادة والري.' },
    metaTitle: { en: 'TIMEX Packaged Water Treatment Systems | C-Water', ar: 'أنظمة معالجة المياه المجمّعة من TIMEX | C-Water' },
    metaDescription: { en: 'TIMEX packaged water treatment systems for drinking water, wastewater treatment, water recovery and irrigation network duty.', ar: 'أنظمة معالجة المياه المجمّعة من TIMEX لمياه الشرب ومعالجة الصرف واستعادة المياه وشبكات الري.' },
    overview: {
      en: 'A packaged system shortens installation and commissioning, but only performs if the duty was defined accurately first. C-Water establishes the design basis before a package is selected.',
      ar: 'يختصر النظام المجمّع وقت التركيب والتشغيل، لكنه لا يؤدي دوره إلا إذا حُددت المهمة بدقة أولًا. وتضع C-Water أساس التصميم قبل اختيار أي حزمة.',
    },
    benefits: [
      { id: 'speed', icon: 'wrench', label: { en: 'Shorter installation', ar: 'تركيب أسرع' }, body: { en: 'Pre-assembled and factory-tested reduces time and risk on site.', ar: 'التجميع المسبق والاختبار في المصنع يقللان الوقت والمخاطر في الموقع.' } },
      { id: 'defined', icon: 'blueprint', label: { en: 'Defined performance envelope', ar: 'نطاق أداء محدد' }, body: { en: 'A package is specified against a duty, which makes verification straightforward.', ar: 'تُحدَّد مواصفة الحزمة مقابل مهمة معينة، مما يجعل التحقق مباشرًا.' } },
    ],
    applications: [
      { en: 'Drinking and potable water systems', ar: 'أنظمة مياه الشرب' },
      { en: 'Wastewater treatment and recovery', ar: 'معالجة مياه الصرف واستعادتها' },
      { en: 'Irrigation network filtration', ar: 'ترشيح شبكات الري' },
      { en: 'Zero-discharge and reuse duty', ar: 'تطبيقات عدم التصريف وإعادة الاستخدام' },
    ],
    specs: [
      { key: { en: 'Type', ar: 'النوع' }, value: { en: 'Packaged / engineered treatment system', ar: 'نظام معالجة مجمّع / مُهندَس' } },
      { key: { en: 'Duty types published by TIMEX', ar: 'أنواع المهام المنشورة من TIMEX' }, value: { en: 'Drinking water, wastewater, recovery / zero discharge, irrigation', ar: 'مياه الشرب، مياه الصرف، الاستعادة / عدم التصريف، الري' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('br', 'Water treatment systems brochure', 'كتيّب أنظمة معالجة المياه', 'brochure')],
    solutions: ['potable-water', 'wastewater', 'process-water', 'industrial-water'],
    industries: ['government-municipal', 'manufacturing', 'hospitality', 'agriculture-irrigation', 'aquaculture'],
    relatedProducts: ['timex-kmf-series', 'timex-hydrospin', 'timex-daf'],
  },

  /* ================= KURITA — CHEMISTRY ================================= */
  {
    slug: 'kurita-cooling-programme',
    status: 'published',
    name: 'Kurita Cooling Water Programmes',
    partner: 'kurita',
    category: 'cooling-chemicals',
    technology: 'water-treatment-chemicals',
    title: { en: 'Cooling Water Treatment Programmes', ar: 'برامج معالجة مياه التبريد' },
    positioning: { en: 'Scale, corrosion and biofouling control designed as one programme.', ar: 'تحكم في الترسبات والتآكل والنمو البيولوجي مصمم كبرنامج واحد.' },
    summary: { en: 'Kurita cooling water chemistry applied against measured analysis and system metallurgy.', ar: 'كيمياء مياه التبريد من Kurita مطبَّقة وفق تحليل مقاس ومعادن النظام.' },
    metaTitle: { en: 'Kurita Cooling Water Treatment Programmes | C-Water', ar: 'برامج Kurita لمعالجة مياه التبريد | C-Water' },
    metaDescription: { en: 'Kurita cooling water treatment chemistry for scale, corrosion and microbiological control, selected and managed through C-Water engineering.', ar: 'كيمياء Kurita لمعالجة مياه التبريد للتحكم في الترسبات والتآكل والميكروبيولوجيا، تختارها وتديرها هندسة C-Water.' },
    overview: {
      en: 'A cooling programme has to hold three objectives at once without the components undermining each other. C-Water selects the combination against the analysis, metallurgy and achievable cycles for the actual system.',
      ar: 'يجب أن يحقق برنامج التبريد ثلاثة أهداف في آن واحد دون أن تُقوّض مكوناته بعضها. وتختار C-Water التركيبة وفق التحليل والمعادن ودورات التركيز الممكنة للنظام الفعلي.',
    },
    benefits: [
      { id: 'integrated', icon: 'flask', label: { en: 'Compatible by design', ar: 'متوافقة بحكم التصميم' }, body: { en: 'Inhibitor, dispersant and biocide chosen as a set so an oxidiser does not degrade the inhibitor protecting the metal.', ar: 'يُختار المثبط والمشتت والمبيد كمجموعة بحيث لا يُفكك المؤكسد المثبطَ الذي يحمي المعدن.' } },
      { id: 'cycles', icon: 'droplet', label: { en: 'Supports higher cycles', ar: 'يدعم دورات تركيز أعلى' }, body: { en: 'Effective scale control is what makes operating at higher cycles of concentration safe.', ar: 'التحكم الفعال في الترسبات هو ما يجعل التشغيل عند دورات تركيز أعلى آمنًا.' } },
      { id: 'verify', icon: 'gauge', label: { en: 'Verifiable in service', ar: 'قابل للتحقق أثناء الخدمة' }, body: { en: 'Control limits and routine testing confirm the programme is achieving what it was chosen for.', ar: 'تؤكد حدود التحكم والاختبار الروتيني أن البرنامج يحقق الغرض الذي اختير له.' } },
    ],
    applications: [
      { en: 'Open recirculating cooling systems', ar: 'أنظمة التبريد المفتوحة ذات الدوران' },
      { en: 'Closed chilled and condenser water', ar: 'مياه التبريد والمكثفات المغلقة' },
      { en: 'Process cooling circuits', ar: 'دوائر تبريد العمليات' },
    ],
    specs: [
      { key: { en: 'Application', ar: 'التطبيق' }, value: { en: 'Cooling water treatment', ar: 'معالجة مياه التبريد' } },
      { key: { en: 'Treatment objectives', ar: 'أهداف المعالجة' }, value: { en: 'Scale, corrosion and microbiological control', ar: 'التحكم في الترسبات والتآكل والميكروبيولوجيا' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('an', 'Cooling water programme application note', 'مذكرة تطبيقية لبرنامج مياه التبريد', 'application-note')],
    solutions: ['cooling-water', 'industrial-water'],
    industries: ['manufacturing', 'power-utilities', 'hospitality', 'commercial-buildings', 'chemical-petrochemical', 'food-beverage'],
    relatedProducts: ['kurita-dilurit-bc', 'walchem-intuition-9', 'timex-svf-series'],
  },

  {
    slug: 'kurita-cetamine',
    status: 'published',
    name: 'Kurita Cetamine®',
    partner: 'kurita',
    category: 'boiler-chemicals',
    technology: 'water-treatment-chemicals',
    title: { en: 'Cetamine® Boiler Water Technology', ar: 'تقنية Cetamine® لمياه الغلايات' },
    positioning: { en: 'Film-forming boiler water chemistry across the full steam cycle.', ar: 'كيمياء مكوِّنة للأغشية لمياه الغلايات عبر دورة البخار كاملة.' },
    summary: { en: 'Kurita’s film-forming amine technology for boiler, steam and condensate protection.', ar: 'تقنية الأمينات المكوِّنة للأغشية من Kurita لحماية الغلاية والبخار والمتكثفات.' },
    metaTitle: { en: 'Kurita Cetamine® Boiler Water Treatment | C-Water', ar: 'معالجة مياه الغلايات بتقنية Kurita Cetamine® | C-Water' },
    metaDescription: { en: 'Kurita Cetamine® film-forming boiler water treatment technology for feedwater, boiler, steam and condensate protection, applied through C-Water engineering.', ar: 'تقنية Kurita Cetamine® المكوِّنة للأغشية لمعالجة مياه الغلايات وحماية مياه التغذية والغلاية والبخار والمتكثفات، عبر هندسة C-Water.' },
    overview: {
      en: 'Cetamine® is Kurita’s film-forming technology for boiler systems. Kurita positions it around reduced conductivity and blowdown demand, and it acts across the whole steam cycle rather than only within the boiler.',
      ar: 'Cetamine® هي تقنية Kurita المكوِّنة للأغشية لأنظمة الغلايات. وتوجّهها Kurita نحو خفض التوصيلية ومعدل التصريف، وتعمل عبر دورة البخار بأكملها لا داخل الغلاية فقط.',
    },
    benefits: [
      { id: 'cycle', icon: 'recycle', label: { en: 'Acts across the whole cycle', ar: 'تعمل عبر الدورة كاملة' }, body: { en: 'Protection extends into the steam and condensate system, where conventional internal treatment does not reach.', ar: 'تمتد الحماية إلى نظام البخار والمتكثفات، حيث لا تصل المعالجة الداخلية التقليدية.' } },
      { id: 'blowdown', icon: 'energy', label: { en: 'Lower blowdown demand', ar: 'متطلب تصريف أقل' }, body: { en: 'Kurita positions the technology around reduced conductivity and therefore reduced blowdown requirement.', ar: 'توجّه Kurita التقنية نحو خفض التوصيلية ومن ثم خفض متطلب التصريف.' } },
    ],
    applications: [
      { en: 'Steam boiler systems', ar: 'أنظمة غلايات البخار' },
      { en: 'Feedwater and condensate protection', ar: 'حماية مياه التغذية والمتكثفات' },
      { en: 'Process steam generation', ar: 'توليد بخار العمليات' },
    ],
    specs: [
      { key: { en: 'Technology', ar: 'التقنية' }, value: { en: 'Kurita Cetamine® film-forming chemistry', ar: 'كيمياء Kurita Cetamine® المكوِّنة للأغشية' } },
      { key: { en: 'Application', ar: 'التطبيق' }, value: { en: 'Boiler, steam and condensate systems', ar: 'أنظمة الغلايات والبخار والمتكثفات' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('an', 'Cetamine® application note', 'مذكرة تطبيقية عن Cetamine®', 'application-note')],
    solutions: ['boiler-steam', 'industrial-water'],
    industries: ['manufacturing', 'food-beverage', 'power-utilities', 'pharmaceutical-cosmetics', 'chemical-petrochemical'],
    relatedProducts: ['walchem-w100', 'walchem-conductivity-sensors', 'walchem-e-series'],
  },

  {
    slug: 'kurita-dilurit-bc',
    status: 'published',
    name: 'Kurita Dilurit® BC S-System',
    partner: 'kurita',
    category: 'cooling-chemicals',
    technology: 'water-treatment-chemicals',
    title: { en: 'Dilurit® BC S-System', ar: 'نظام Dilurit® BC S-System' },
    positioning: { en: 'Monochloramine-based microbiological control for cooling water.', ar: 'تحكم ميكروبيولوجي قائم على المونوكلورامين لمياه التبريد.' },
    summary: { en: 'Kurita’s monochloramine chemistry for cooling water biological control.', ar: 'كيمياء المونوكلورامين من Kurita للتحكم البيولوجي في مياه التبريد.' },
    metaTitle: { en: 'Kurita Dilurit® BC S-System | C-Water', ar: 'نظام Kurita Dilurit® BC S-System | C-Water' },
    metaDescription: { en: 'Kurita Dilurit® BC S-System monochloramine cooling water treatment for microbiological and biofilm control, applied through C-Water engineering.', ar: 'نظام Kurita Dilurit® BC S-System بالمونوكلورامين لمعالجة مياه التبريد والتحكم الميكروبيولوجي والأغشية الحيوية، عبر هندسة C-Water.' },
    overview: {
      en: 'Kurita’s Dilurit® BC S-System applies monochloramine chemistry to cooling water microbiological control. Biofilm is the target that matters most, because an established film insulates heat-transfer surface and shelters what lies beneath it.',
      ar: 'يطبق نظام Kurita Dilurit® BC S-System كيمياء المونوكلورامين للتحكم الميكروبيولوجي في مياه التبريد. والغشاء الحيوي هو الهدف الأهم، لأن الغشاء المستقر يعزل سطح التبادل الحراري ويحمي ما تحته.',
    },
    benefits: [
      { id: 'biofilm', icon: 'biology', label: { en: 'Targets established biofilm', ar: 'يستهدف الأغشية الحيوية المستقرة' }, body: { en: 'Planktonic count alone is a poor measure of biological control; surface condition is the objective.', ar: 'العدّ الطليق وحده مقياس ضعيف للتحكم البيولوجي، والهدف هو حالة السطح.' } },
      { id: 'compatible', icon: 'flask', label: { en: 'Programme compatibility', ar: 'توافق مع البرنامج' }, body: { en: 'Biocide selection has to sit alongside the inhibitor chemistry without degrading it.', ar: 'يجب أن يتوافق اختيار المبيد مع كيمياء المثبطات دون أن يُفككها.' } },
    ],
    applications: [
      { en: 'Open recirculating cooling systems', ar: 'أنظمة التبريد المفتوحة ذات الدوران' },
      { en: 'High-fouling-risk cooling duty', ar: 'تطبيقات التبريد عالية مخاطر الاتساخ' },
    ],
    specs: [
      { key: { en: 'Technology', ar: 'التقنية' }, value: { en: 'Kurita Dilurit® BC S-System', ar: 'Kurita Dilurit® BC S-System' } },
      { key: { en: 'Chemistry', ar: 'الكيمياء' }, value: { en: 'Monochloramine-based', ar: 'قائمة على المونوكلورامين' } },
      { key: { en: 'Objective', ar: 'الهدف' }, value: { en: 'Microbiological and biofilm control', ar: 'التحكم الميكروبيولوجي وفي الأغشية الحيوية' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('an', 'Dilurit® BC S-System application note', 'مذكرة تطبيقية عن Dilurit® BC S-System', 'application-note')],
    solutions: ['cooling-water', 'industrial-water'],
    industries: ['manufacturing', 'power-utilities', 'chemical-petrochemical', 'hospitality', 'food-beverage'],
    relatedProducts: ['kurita-cooling-programme', 'walchem-ph-orp-sensors', 'walchem-intuition-9'],
  },

  {
    slug: 'kurita-kuriverter-ik110',
    status: 'published',
    name: 'Kurita Kuriverter® IK-110',
    partner: 'kurita',
    category: 'membrane-chemicals',
    technology: 'water-treatment-chemicals',
    title: { en: 'Kuriverter® IK-110', ar: 'Kuriverter® IK-110' },
    positioning: { en: 'Biofouling control for membrane systems.', ar: 'التحكم في النمو البيولوجي لأنظمة الأغشية.' },
    summary: { en: 'Kurita membrane chemistry addressing biofouling in desalination and RO duty.', ar: 'كيمياء أغشية من Kurita تعالج النمو البيولوجي في تطبيقات التحلية والتناضح العكسي.' },
    metaTitle: { en: 'Kurita Kuriverter® IK-110 Membrane Treatment | C-Water', ar: 'معالجة الأغشية Kurita Kuriverter® IK-110 | C-Water' },
    metaDescription: { en: 'Kurita Kuriverter® IK-110 for biofouling reduction in membrane and desalination systems, applied within a complete C-Water RO treatment strategy.', ar: 'Kurita Kuriverter® IK-110 لخفض النمو البيولوجي في أنظمة الأغشية والتحلية، ضمن استراتيجية معالجة متكاملة للتناضح العكسي من C-Water.' },
    overview: {
      en: 'Kurita positions Kuriverter® IK-110 around biofouling reduction in desalination duty. C-Water applies membrane chemistry only as part of a complete strategy — chemistry does not compensate for pretreatment that is not doing its job.',
      ar: 'توجّه Kurita منتج Kuriverter® IK-110 نحو خفض النمو البيولوجي في تطبيقات التحلية. وتطبق C-Water كيمياء الأغشية كجزء من استراتيجية متكاملة فقط — فالكيمياء لا تعوّض عن معالجة أولية لا تؤدي دورها.',
    },
    benefits: [
      { id: 'biofouling', icon: 'biology', label: { en: 'Addresses biological fouling', ar: 'يعالج الاتساخ البيولوجي' }, body: { en: 'Biological fouling is among the hardest membrane conditions to reverse once established.', ar: 'الاتساخ البيولوجي من أصعب حالات الأغشية في التصحيح بعد استقراره.' } },
      { id: 'cleaning', icon: 'recycle', label: { en: 'Supports cleaning interval', ar: 'يدعم فترة التنظيف' }, body: { en: 'Every clean costs downtime, chemical and a small amount of membrane life.', ar: 'كل تنظيف يكلف توقفًا وكيماويات وقدرًا صغيرًا من عمر الغشاء.' } },
    ],
    applications: [
      { en: 'RO and membrane systems', ar: 'أنظمة التناضح العكسي والأغشية' },
      { en: 'Desalination duty', ar: 'تطبيقات التحلية' },
      { en: 'Water recovery and reuse', ar: 'استعادة المياه وإعادة استخدامها' },
    ],
    specs: [
      { key: { en: 'Technology', ar: 'التقنية' }, value: { en: 'Kurita Kuriverter® IK-110', ar: 'Kurita Kuriverter® IK-110' } },
      { key: { en: 'Application', ar: 'التطبيق' }, value: { en: 'Membrane systems and desalination', ar: 'أنظمة الأغشية والتحلية' } },
      { key: { en: 'Objective', ar: 'الهدف' }, value: { en: 'Biofouling reduction', ar: 'خفض النمو البيولوجي' } },
    ],
    specsPendingReview: true,
    documents: [onRequestDoc('an', 'Kuriverter® IK-110 application note', 'مذكرة تطبيقية عن Kuriverter® IK-110', 'application-note')],
    solutions: ['ro-membranes', 'process-water', 'potable-water'],
    industries: ['manufacturing', 'food-beverage', 'healthcare', 'pharmaceutical-cosmetics', 'power-utilities', 'oil-gas'],
    relatedProducts: ['timex-cartridge-filter', 'timex-svf-series', 'walchem-conductivity-sensors'],
  },
];

export const productBySlug = Object.fromEntries(products.map((p) => [p.slug, p]));

/** Catalogue category labels, used by the filter bar and product pages. */
export const productCategories: Record<Product['category'], { en: string; ar: string }> = {
  controllers: { en: 'Controllers', ar: 'وحدات التحكم' },
  sensors: { en: 'Sensors', ar: 'المستشعرات' },
  'metering-pumps': { en: 'Metering Pumps', ar: 'مضخات الجرعات' },
  software: { en: 'Monitoring Software', ar: 'برمجيات المراقبة' },
  'self-cleaning-filters': { en: 'Self-Cleaning Filters', ar: 'مرشحات ذاتية التنظيف' },
  'cartridge-filters': { en: 'Cartridge Filters', ar: 'مرشحات الخراطيش' },
  'disc-filters': { en: 'Disc Filters', ar: 'مرشحات الأقراص' },
  separators: { en: 'Separators', ar: 'الفواصل' },
  flotation: { en: 'Flotation', ar: 'التعويم' },
  'screens-strainers': { en: 'Screens & Strainers', ar: 'الشاشات والمصافي' },
  'treatment-systems': { en: 'Treatment Systems', ar: 'أنظمة المعالجة' },
  'cooling-chemicals': { en: 'Cooling Water Chemistry', ar: 'كيمياء مياه التبريد' },
  'boiler-chemicals': { en: 'Boiler Water Chemistry', ar: 'كيمياء مياه الغلايات' },
  'membrane-chemicals': { en: 'Membrane Chemistry', ar: 'كيمياء الأغشية' },
  'wastewater-chemicals': { en: 'Wastewater Chemistry', ar: 'كيمياء مياه الصرف' },
};
