import type { Service } from './types';

/**
 * Services.
 *
 * The narrative across all nine is the same: the equipment is one part of the
 * solution. `verb` is the short form used in the six-step services diagram.
 */
export const services: Service[] = [
  {
    slug: 'water-analysis',
    status: 'published',
    icon: 'lab',
    verb: { en: 'Analyse', ar: 'حلّل' },
    title: { en: 'Water Analysis', ar: 'تحليل المياه' },
    headline: { en: 'Know the Water Before Deciding Anything.', ar: 'اعرف المياه قبل أن تقرر أي شيء.' },
    summary: { en: 'Sampling, analysis and interpretation against the system the water is actually in.', ar: 'أخذ العينات والتحليل والتفسير في ضوء النظام الذي توجد فيه المياه فعلًا.' },
    metaTitle: { en: 'Industrial Water Analysis Service | C-Water', ar: 'خدمة تحليل المياه الصناعية | C-Water' },
    metaDescription: { en: 'Water sampling, laboratory analysis and engineering interpretation for industrial and commercial water systems, as the basis for treatment decisions.', ar: 'أخذ عينات المياه، والتحليل المعملي، والتفسير الهندسي لأنظمة المياه الصناعية والتجارية، كأساس لقرارات المعالجة.' },
    whatItIs: { en: 'A structured sampling and analysis exercise that establishes what is in the water, how it varies, and what that means for the equipment it passes through.', ar: 'عملية منهجية لأخذ العينات والتحليل تحدد ما تحتويه المياه، وكيف يتغير، وماذا يعني ذلك للمعدات التي تمر بها.' },
    whyItMatters: { en: 'Analysis is the least expensive step in any treatment programme and the one that determines whether the rest of it was correctly chosen. A programme selected without it is selected from a catalogue.', ar: 'التحليل أقل خطوات أي برنامج معالجة تكلفة، وهو الذي يحدد ما إذا كان اختيار بقيته صحيحًا. فالبرنامج المختار بدونه مختار من كتالوج.' },
    whenYouNeedIt: [
      { id: 'new', icon: 'blueprint', label: { en: 'Before designing a new system', ar: 'قبل تصميم نظام جديد' }, body: { en: 'The source water defines the treatment train. Nothing else can be sized until it is known.', ar: 'مياه المصدر هي التي تحدد سلسلة المعالجة. ولا يمكن تحجيم أي شيء آخر قبل معرفتها.' } },
      { id: 'problem', icon: 'wrench', label: { en: 'When something is going wrong', ar: 'عند حدوث خلل' }, body: { en: 'Deposits, corrosion or unexplained consumption all have a chemical explanation that analysis can find.', ar: 'للرواسب أو التآكل أو الاستهلاك غير المفسر تفسير كيميائي يمكن للتحليل الوصول إليه.' } },
      { id: 'change', icon: 'flow', label: { en: 'When the source changes', ar: 'عند تغير المصدر' }, body: { en: 'A new supply, a new well or a seasonal shift can invalidate a programme that had been working.', ar: 'قد يُبطل إمداد جديد أو بئر جديد أو تحول موسمي برنامجًا كان يعمل بكفاءة.' } },
      { id: 'review', icon: 'clipboard', label: { en: 'As routine verification', ar: 'كتحقق دوري' }, body: { en: 'Periodic analysis confirms the programme is still holding the system where it was designed to.', ar: 'يؤكد التحليل الدوري أن البرنامج لا يزال يبقي النظام عند الحالة المصممة له.' } },
    ],
    approach: [
      { id: 'plan', icon: 'clipboard', label: { en: 'Plan the sampling', ar: 'تخطيط أخذ العينات' }, body: { en: 'Sample points, timing and method chosen so the result describes the system rather than a moment in it.', ar: 'تُختار نقاط أخذ العينات وتوقيتها وطريقتها بحيث تصف النتيجة النظام لا لحظة فيه.' } },
      { id: 'analyse', icon: 'lab', label: { en: 'Analyse', ar: 'التحليل' }, body: { en: 'The parameter set is chosen for the application — cooling, boiler, RO and effluent each require a different panel.', ar: 'تُختار مجموعة المتغيرات وفق التطبيق — فالتبريد والغلايات والتناضح العكسي والمخلفات يحتاج كل منها لوحة مختلفة.' } },
      { id: 'interpret', icon: 'blueprint', label: { en: 'Interpret against the system', ar: 'التفسير في ضوء النظام' }, body: { en: 'Results are read against metallurgy, temperature, cycles and duty, not against a generic reference table.', ar: 'تُقرأ النتائج في ضوء المعادن ودرجة الحرارة ودورات التركيز وظروف التشغيل، لا مقابل جدول مرجعي عام.' } },
      { id: 'recommend', icon: 'flask', label: { en: 'Recommend', ar: 'التوصية' }, body: { en: 'A clear statement of what the water will do to the system and what has to change.', ar: 'بيان واضح لما ستفعله المياه بالنظام وما الذي يجب تغييره.' } },
    ],
    deliverables: [
      { en: 'Analytical results against the relevant parameter set', ar: 'نتائج تحليلية مقابل مجموعة المتغيرات المعنية' },
      { en: 'Interpretation referenced to your system and operating conditions', ar: 'تفسير مرتبط بنظامك وظروف تشغيلك' },
      { en: 'Scaling and corrosion tendency assessment', ar: 'تقييم ميل الترسب والتآكل' },
      { en: 'Recommended treatment direction and control limits', ar: 'الاتجاه العلاجي الموصى به وحدود التحكم' },
      { en: 'A baseline for future comparison', ar: 'خط أساس للمقارنة المستقبلية' },
    ],
    technologies: ['water-analysis', 'water-treatment-chemicals', 'sensors-measurement'],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'process-water', 'wastewater', 'potable-water'],
    cta: { en: 'Request Water Analysis', ar: 'اطلب تحليل مياه' },
  },

  {
    slug: 'system-assessment',
    status: 'published',
    icon: 'gauge',
    verb: { en: 'Assess', ar: 'قيّم' },
    title: { en: 'System Assessment', ar: 'تقييم النظام' },
    headline: { en: 'Find Out What the System Is Actually Doing.', ar: 'اكتشف ما يفعله النظام فعليًا.' },
    summary: { en: 'A structured survey of condition, control quality, risk and improvement opportunity.', ar: 'مسح منهجي للحالة وجودة التحكم والمخاطر وفرص التحسين.' },
    metaTitle: { en: 'Water System Assessment & Survey | C-Water', ar: 'تقييم ومسح أنظمة المياه | C-Water' },
    metaDescription: { en: 'On-site water system assessment covering equipment condition, control performance, treatment effectiveness, risk and prioritised improvement opportunities.', ar: 'تقييم ميداني لأنظمة المياه يشمل حالة المعدات، وأداء التحكم، وفعالية المعالجة، والمخاطر، وفرص التحسين مرتبة بالأولوية.' },
    whatItIs: { en: 'A site visit that documents what is installed, what condition it is in, how it is being controlled and where the gaps between design intent and current operation lie.', ar: 'زيارة ميدانية توثّق ما هو مركّب، وحالته، وكيف يُتحكم فيه، وأين تقع الفجوات بين نية التصميم والتشغيل الحالي.' },
    whyItMatters: { en: 'Most water systems have drifted from how they were designed to run. Setpoints were changed, a pump was replaced with what was available, a filter was bypassed during a shutdown and never returned to service.', ar: 'انحرفت معظم أنظمة المياه عن الطريقة التي صُممت للعمل بها. فقد غُيّرت نقاط الضبط، واستُبدلت مضخة بما كان متاحًا، وجرى تجاوز مرشح أثناء توقف ولم يُعَد إلى الخدمة قط.' },
    whenYouNeedIt: [
      { id: 'inherited', icon: 'clipboard', label: { en: 'You inherited the system', ar: 'ورثت النظام' }, body: { en: 'New responsibility for plant whose history and design intent are not documented.', ar: 'مسؤولية جديدة عن منشأة لم يُوثَّق تاريخها ولا نية تصميمها.' } },
      { id: 'cost', icon: 'energy', label: { en: 'Costs are rising without explanation', ar: 'ارتفاع التكاليف دون تفسير' }, body: { en: 'Chemical, water or energy consumption trending upward is a symptom worth tracing.', ar: 'ارتفاع استهلاك الكيماويات أو المياه أو الطاقة عرَض يستحق تتبعه.' } },
      { id: 'recurring', icon: 'wrench', label: { en: 'A problem keeps returning', ar: 'مشكلة تتكرر' }, body: { en: 'Repeated cleaning, repeated failures or repeated deviations point to a cause that has not been found.', ar: 'تكرار التنظيف أو الأعطال أو الانحرافات يشير إلى سبب لم يُكتشف بعد.' } },
      { id: 'change', icon: 'factory', label: { en: 'Before a capacity or process change', ar: 'قبل تغيير السعة أو العملية' }, body: { en: 'Knowing the current margin before adding load avoids discovering it afterwards.', ar: 'معرفة الهامش الحالي قبل إضافة حمل تجنّبك اكتشافه لاحقًا.' } },
    ],
    approach: [
      { id: 'survey', icon: 'blueprint', label: { en: 'Survey what is installed', ar: 'مسح ما هو مركّب' }, body: { en: 'Equipment, arrangement, instrumentation and their actual condition rather than the drawing.', ar: 'المعدات والترتيب وأجهزة القياس وحالتها الفعلية لا كما في المخطط.' } },
      { id: 'measure', icon: 'gauge', label: { en: 'Measure the operating point', ar: 'قياس نقطة التشغيل' }, body: { en: 'Water chemistry, control settings, differential pressures and consumption records.', ar: 'كيمياء المياه، وإعدادات التحكم، وفروق الضغط، وسجلات الاستهلاك.' } },
      { id: 'gap', icon: 'clipboard', label: { en: 'Identify the gaps', ar: 'تحديد الفجوات' }, body: { en: 'Between design intent, current operation and what the application actually requires.', ar: 'بين نية التصميم والتشغيل الحالي وما يتطلبه التطبيق فعليًا.' } },
      { id: 'prioritise', icon: 'optimize', label: { en: 'Prioritise', ar: 'ترتيب الأولويات' }, body: { en: 'Findings ordered by risk and by return, so a limited budget goes to the right item first.', ar: 'تُرتَّب النتائج وفق المخاطر والعائد، لتذهب الميزانية المحدودة إلى البند الصحيح أولًا.' } },
    ],
    deliverables: [
      { en: 'Documented system description and condition record', ar: 'وصف موثق للنظام وسجل لحالته' },
      { en: 'Control performance review against the treatment objective', ar: 'مراجعة أداء التحكم مقابل هدف المعالجة' },
      { en: 'Identified risks with their operational consequence', ar: 'مخاطر محددة مع أثرها التشغيلي' },
      { en: 'Prioritised improvement recommendations', ar: 'توصيات تحسين مرتبة بالأولوية' },
    ],
    technologies: ['water-analysis', 'engineering-integration', 'monitoring-control', 'filtration'],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'industrial-water', 'wastewater'],
    cta: { en: 'Request a System Assessment', ar: 'اطلب تقييم نظام' },
  },

  {
    slug: 'engineering-design',
    status: 'published',
    icon: 'blueprint',
    verb: { en: 'Engineer', ar: 'صمّم' },
    title: { en: 'Engineering & Design', ar: 'الهندسة والتصميم' },
    headline: { en: 'Design That Accounts for How It Will Be Operated.', ar: 'تصميم يراعي كيف سيُشغَّل.' },
    summary: { en: 'Treatment schemes sized from measured data and specified so they can be built, run and maintained.', ar: 'مخططات معالجة محجّمة من بيانات مقاسة وموصّفة بحيث يمكن بناؤها وتشغيلها وصيانتها.' },
    metaTitle: { en: 'Water Treatment Engineering & Design | C-Water', ar: 'هندسة وتصميم معالجة المياه | C-Water' },
    metaDescription: { en: 'Water treatment design: treatment train selection, equipment sizing, hydraulic and control design, specification and documentation for industrial water systems.', ar: 'تصميم معالجة المياه: اختيار سلسلة المعالجة، وتحجيم المعدات، والتصميم الهيدروليكي والتحكمي، والمواصفات والتوثيق لأنظمة المياه الصناعية.' },
    whatItIs: { en: 'The engineering work between knowing what the water is and having a system that deals with it: treatment train, sizing, hydraulics, control philosophy, layout and specification.', ar: 'العمل الهندسي بين معرفة حال المياه وامتلاك نظام يتعامل معها: سلسلة المعالجة، والتحجيم، والهيدروليكا، وفلسفة التحكم، والتخطيط، والمواصفات.' },
    whyItMatters: { en: 'Equipment can be bought quickly. A system that produces the right water at the right rate, can be maintained without a shutdown and does not need an expert present to operate takes design.', ar: 'يمكن شراء المعدات بسرعة. أما النظام الذي ينتج المياه الصحيحة بالمعدل الصحيح، ويمكن صيانته دون إيقاف، ولا يحتاج خبيرًا حاضرًا لتشغيله، فيحتاج تصميمًا.' },
    whenYouNeedIt: [
      { id: 'new', icon: 'factory', label: { en: 'New plant or new line', ar: 'منشأة أو خط إنتاج جديد' }, body: { en: 'Where the water requirement is being defined for the first time.', ar: 'حيث يجري تحديد متطلبات المياه لأول مرة.' } },
      { id: 'upgrade', icon: 'wrench', label: { en: 'Upgrade or retrofit', ar: 'ترقية أو إعادة تأهيل' }, body: { en: 'Adding capability to an existing system without disturbing what already works.', ar: 'إضافة قدرات إلى نظام قائم دون الإخلال بما يعمل بالفعل.' } },
      { id: 'capacity', icon: 'flow', label: { en: 'Capacity change', ar: 'تغيير السعة' }, body: { en: 'Increasing throughput usually moves more than one constraint at a time.', ar: 'زيادة الطاقة الإنتاجية تحرّك عادةً أكثر من قيد واحد في وقت واحد.' } },
      { id: 'spec', icon: 'clipboard', label: { en: 'Tender specification', ar: 'مواصفة مناقصة' }, body: { en: 'A technically complete specification is what makes competing offers comparable.', ar: 'المواصفة الفنية الكاملة هي ما يجعل العروض المتنافسة قابلة للمقارنة.' } },
    ],
    approach: [
      { id: 'basis', icon: 'lab', label: { en: 'Establish the design basis', ar: 'وضع أساس التصميم' }, body: { en: 'Source water range, output specification, flow profile and the operating constraints that are non-negotiable.', ar: 'نطاق مياه المصدر، ومواصفة المخرجات، ومنحنى التدفق، وقيود التشغيل غير القابلة للتفاوض.' } },
      { id: 'select', icon: 'network', label: { en: 'Select and sequence', ar: 'الاختيار والترتيب' }, body: { en: 'The treatment train, with each stage sized against what reaches it rather than against the intake.', ar: 'سلسلة المعالجة، مع تحجيم كل مرحلة وفق ما يصل إليها لا وفق المأخذ.' } },
      { id: 'detail', icon: 'blueprint', label: { en: 'Detail the design', ar: 'تفصيل التصميم' }, body: { en: 'Hydraulics, materials, instrumentation, control interfaces, access and maintenance space.', ar: 'الهيدروليكا والمواد وأجهزة القياس ووصلات التحكم والوصول ومساحة الصيانة.' } },
      { id: 'document', icon: 'clipboard', label: { en: 'Document it', ar: 'التوثيق' }, body: { en: 'Specification, control philosophy and operating description that survive staff changes.', ar: 'مواصفة وفلسفة تحكم ووصف تشغيلي تصمد أمام تغير الكوادر.' } },
    ],
    deliverables: [
      { en: 'Design basis and treatment scheme', ar: 'أساس التصميم ومخطط المعالجة' },
      { en: 'Equipment sizing and technical specification', ar: 'تحجيم المعدات والمواصفة الفنية' },
      { en: 'Control philosophy and instrumentation schedule', ar: 'فلسفة التحكم وجدول أجهزة القياس' },
      { en: 'Layout and interface requirements', ar: 'متطلبات التخطيط والوصلات' },
      { en: 'Operating description for handover', ar: 'وصف تشغيلي للتسليم' },
    ],
    technologies: ['engineering-integration', 'filtration', 'reverse-osmosis', 'monitoring-control', 'water-analysis'],
    solutions: ['process-water', 'industrial-water', 'wastewater', 'ro-membranes', 'potable-water'],
    cta: { en: 'Start a Technical Discussion', ar: 'ابدأ نقاشًا فنيًا' },
  },

  {
    slug: 'installation-commissioning',
    status: 'published',
    icon: 'wrench',
    verb: { en: 'Install', ar: 'ركّب' },
    title: { en: 'Installation & Commissioning', ar: 'التركيب والتشغيل الابتدائي' },
    headline: { en: 'Bring the System Into Service Properly.', ar: 'أدخل النظام إلى الخدمة على النحو الصحيح.' },
    summary: { en: 'Installation, setup, verification and the handover that makes the system operable by the people who own it.', ar: 'التركيب والإعداد والتحقق والتسليم الذي يجعل النظام قابلًا للتشغيل من قِبل مالكيه.' },
    metaTitle: { en: 'Water Treatment Installation & Commissioning | C-Water', ar: 'تركيب وتشغيل أنظمة معالجة المياه | C-Water' },
    metaDescription: { en: 'Installation and commissioning of water treatment equipment: mechanical fitting, control configuration, functional testing, verification and documented handover.', ar: 'تركيب وتشغيل معدات معالجة المياه: التركيب الميكانيكي، وضبط التحكم، والاختبار الوظيفي، والتحقق، والتسليم الموثق.' },
    whatItIs: { en: 'Physical installation, control configuration, functional verification and a handover that leaves the site able to run and troubleshoot the system.', ar: 'تركيب فعلي، وضبط للتحكم، وتحقق وظيفي، وتسليم يترك الموقع قادرًا على تشغيل النظام واستكشاف أعطاله.' },
    whyItMatters: { en: 'Commissioning is where a specification becomes a working system or a set of defaults. Setpoints left at factory values, an injection point in the wrong place or a sensor installed where it cannot read properly all originate here.', ar: 'التشغيل الابتدائي هو الموضع الذي تتحول فيه المواصفة إلى نظام عامل أو إلى مجموعة إعدادات افتراضية. فنقاط ضبط تُركت على قيم المصنع، أو نقطة حقن في موضع خاطئ، أو مستشعر رُكّب حيث لا يقرأ بشكل صحيح — كلها تنشأ هنا.' },
    whenYouNeedIt: [
      { id: 'new', icon: 'blueprint', label: { en: 'New equipment', ar: 'معدات جديدة' }, body: { en: 'Any new controller, pump, filter or treatment skid entering service.', ar: 'أي وحدة تحكم أو مضخة أو مرشح أو وحدة معالجة جديدة تدخل الخدمة.' } },
      { id: 'programme', icon: 'flask', label: { en: 'New treatment programme', ar: 'برنامج معالجة جديد' }, body: { en: 'Changing chemistry usually means changing setpoints, feed rates and verification method.', ar: 'تغيير الكيمياء يعني عادةً تغيير نقاط الضبط ومعدلات الضخ وطريقة التحقق.' } },
      { id: 'restart', icon: 'factory', label: { en: 'Return to service', ar: 'العودة إلى الخدمة' }, body: { en: 'Bringing a system back after an extended shutdown is a commissioning exercise, not a restart.', ar: 'إعادة نظام إلى العمل بعد توقف طويل عملية تشغيل ابتدائي لا مجرد بدء تشغيل.' } },
    ],
    approach: [
      { id: 'install', icon: 'wrench', label: { en: 'Install', ar: 'التركيب' }, body: { en: 'Mechanical and electrical fitting, with injection and sample points placed where the design requires.', ar: 'تركيب ميكانيكي وكهربائي، مع وضع نقاط الحقن وأخذ العينات حيث يتطلب التصميم.' } },
      { id: 'configure', icon: 'controller', label: { en: 'Configure', ar: 'الضبط' }, body: { en: 'Setpoints, deadbands, feed limits, alarm thresholds and lockouts set for the application, not left at default.', ar: 'تُضبط نقاط الضبط والنطاقات الميتة وحدود الضخ وعتبات الإنذار والحجب وفق التطبيق، ولا تُترك على الإعدادات الافتراضية.' } },
      { id: 'verify', icon: 'gauge', label: { en: 'Verify', ar: 'التحقق' }, body: { en: 'Functional testing across the operating range, including what happens on a lost signal or an empty drum.', ar: 'اختبار وظيفي عبر نطاق التشغيل، بما في ذلك ما يحدث عند فقد إشارة أو نفاد برميل.' } },
      { id: 'handover', icon: 'clipboard', label: { en: 'Hand over', ar: 'التسليم' }, body: { en: 'Recorded settings, operating description and training for the people who will run it.', ar: 'إعدادات مسجلة ووصف تشغيلي وتدريب لمن سيشغّلونه.' } },
    ],
    deliverables: [
      { en: 'Installed and functionally tested equipment', ar: 'معدات مركبة ومختبرة وظيفيًا' },
      { en: 'Recorded configuration and control settings', ar: 'سجل للتهيئة وإعدادات التحكم' },
      { en: 'Commissioning test record', ar: 'سجل اختبارات التشغيل الابتدائي' },
      { en: 'Operating description and site training', ar: 'وصف تشغيلي وتدريب في الموقع' },
    ],
    technologies: ['chemical-dosing', 'monitoring-control', 'filtration', 'engineering-integration'],
    solutions: ['cooling-water', 'boiler-steam', 'process-water', 'wastewater'],
    cta: { en: 'Discuss Your Installation', ar: 'ناقش عملية التركيب لديك' },
  },

  {
    slug: 'chemical-treatment-programmes',
    status: 'published',
    icon: 'flask',
    verb: { en: 'Treat', ar: 'عالِج' },
    title: { en: 'Chemical Treatment Programmes', ar: 'برامج المعالجة الكيميائية' },
    headline: { en: 'A Programme, Not a Product List.', ar: 'برنامج، لا قائمة منتجات.' },
    summary: { en: 'Chemistry selected, dosed, verified and reviewed as one ongoing programme.', ar: 'كيمياء تُختار وتُضخ ويُتحقَّق منها وتُراجَع كبرنامج مستمر واحد.' },
    metaTitle: { en: 'Chemical Treatment Programmes | C-Water', ar: 'برامج المعالجة الكيميائية | C-Water' },
    metaDescription: { en: 'Managed water treatment programmes covering chemistry selection, dosing setup, control limits, routine verification and periodic technical review.', ar: 'برامج معالجة مياه مُدارة تشمل اختيار الكيمياء، وإعداد الجرعات، وحدود التحكم، والتحقق الروتيني، والمراجعة الفنية الدورية.' },
    whatItIs: { en: 'An ongoing arrangement covering the chemistry, the dosing equipment, the control limits, the routine testing and the technical review that keeps the programme matched to the system.', ar: 'ترتيب مستمر يغطي الكيمياء ومعدات الضخ وحدود التحكم والاختبار الروتيني والمراجعة الفنية التي تبقي البرنامج ملائمًا للنظام.' },
    whyItMatters: { en: 'Supplying a chemical is a transaction. Holding a system at its control limits through changing load, changing make-up water and changing seasons is a programme.', ar: 'توريد كيماوي معاملة تجارية. أما إبقاء نظام عند حدود تحكمه عبر تغير الحمل ومياه التعويض والفصول فهو برنامج.' },
    whenYouNeedIt: [
      { id: 'ongoing', icon: 'recycle', label: { en: 'Any system in continuous service', ar: 'أي نظام في خدمة مستمرة' }, body: { en: 'Cooling, boiler and process systems all need chemistry maintained rather than supplied.', ar: 'أنظمة التبريد والغلايات والعمليات تحتاج جميعها كيمياء تُصان لا تُورَّد.' } },
      { id: 'capability', icon: 'wrench', label: { en: 'Limited in-house capability', ar: 'قدرات داخلية محدودة' }, body: { en: 'Where nobody on site has water treatment as their main responsibility.', ar: 'حيث لا يكون لدى أحد في الموقع معالجة المياه كمسؤولية أساسية.' } },
      { id: 'result', icon: 'optimize', label: { en: 'Existing programme not delivering', ar: 'برنامج قائم لا يحقق النتيجة' }, body: { en: 'Chemistry is being dosed but the system condition is not improving.', ar: 'تُضخ الكيماويات لكن حالة النظام لا تتحسن.' } },
    ],
    approach: [
      { id: 'select', icon: 'flask', label: { en: 'Select', ar: 'الاختيار' }, body: { en: 'Chemistry chosen against the analysis, the metallurgy and the duty — as a compatible set, not item by item.', ar: 'تُختار الكيمياء وفق التحليل والمعادن وظروف التشغيل — كمجموعة متوافقة لا بندًا بندًا.' } },
      { id: 'limits', icon: 'gauge', label: { en: 'Set control limits', ar: 'تحديد حدود التحكم' }, body: { en: 'Target ranges for each controlled parameter, with the action to take when a limit is passed.', ar: 'نطاقات مستهدفة لكل متغير محكوم، مع الإجراء الواجب عند تجاوز الحد.' } },
      { id: 'verify', icon: 'clipboard', label: { en: 'Verify routinely', ar: 'التحقق الروتيني' }, body: { en: 'Scheduled testing that confirms the programme is achieving what it was designed to achieve.', ar: 'اختبار مجدول يؤكد أن البرنامج يحقق ما صُمم لتحقيقه.' } },
      { id: 'review', icon: 'optimize', label: { en: 'Review periodically', ar: 'المراجعة الدورية' }, body: { en: 'Trends, consumption and system condition reviewed together so the programme follows the plant.', ar: 'تُراجَع الاتجاهات والاستهلاك وحالة النظام معًا ليتبع البرنامج المنشأة.' } },
    ],
    deliverables: [
      { en: 'Defined treatment programme with control limits', ar: 'برنامج معالجة محدد بحدود تحكم' },
      { en: 'Dosing equipment set up and verified', ar: 'معدات ضخ مُعدّة ومُتحقَّق منها' },
      { en: 'Routine test schedule and record', ar: 'جدول وسجل الاختبارات الروتينية' },
      { en: 'Periodic technical review report', ar: 'تقرير مراجعة فنية دوري' },
    ],
    technologies: ['water-treatment-chemicals', 'chemical-dosing', 'sensors-measurement', 'monitoring-control'],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'wastewater'],
    cta: { en: 'Discuss a Treatment Programme', ar: 'ناقش برنامج معالجة' },
  },

  {
    slug: 'preventive-maintenance',
    status: 'published',
    icon: 'wrench',
    verb: { en: 'Maintain', ar: 'صُن' },
    title: { en: 'Preventive Maintenance', ar: 'الصيانة الوقائية' },
    headline: { en: 'Keep the System Doing What It Was Set Up to Do.', ar: 'أبقِ النظام يفعل ما أُعدّ لفعله.' },
    summary: { en: 'Scheduled attention to the components whose quiet failure undermines everything else.', ar: 'عناية مجدولة بالمكونات التي يقوّض عطلها الصامت كل ما عداها.' },
    metaTitle: { en: 'Water Treatment Preventive Maintenance | C-Water', ar: 'الصيانة الوقائية لمعالجة المياه | C-Water' },
    metaDescription: { en: 'Scheduled maintenance for water treatment systems: sensor calibration, dosing equipment service, filter inspection, control verification and condition reporting.', ar: 'صيانة مجدولة لأنظمة معالجة المياه: معايرة المستشعرات، وخدمة معدات الضخ، وفحص المرشحات، والتحقق من التحكم، وتقارير الحالة.' },
    whatItIs: { en: 'A scheduled service covering sensor calibration, dosing equipment, filter condition, control verification and a documented record of what was found.', ar: 'خدمة مجدولة تغطي معايرة المستشعرات ومعدات الضخ وحالة المرشحات والتحقق من التحكم وسجلًا موثقًا لما تم اكتشافه.' },
    whyItMatters: { en: 'The components that quietly fail are the ones everything else depends on. A drifting pH electrode does not announce itself — it just makes every subsequent decision slightly wrong, for months.', ar: 'المكونات التي تتعطل بصمت هي التي يعتمد عليها كل شيء آخر. فقطب pH المنحرف لا يعلن عن نفسه — بل يجعل كل قرار لاحق خاطئًا قليلًا، لشهور.' },
    whenYouNeedIt: [
      { id: 'always', icon: 'recycle', label: { en: 'Any instrumented system', ar: 'أي نظام مزوّد بأجهزة قياس' }, body: { en: 'Sensors drift and pumps wear. Both are predictable and both are cheap to address on schedule.', ar: 'تنحرف المستشعرات وتتآكل المضخات. وكلاهما متوقع ورخيص المعالجة وفق جدول.' } },
      { id: 'critical', icon: 'shield', label: { en: 'Where availability matters', ar: 'حيث تهم الجاهزية' }, body: { en: 'Systems whose failure interrupts production or occupancy justify a shorter interval.', ar: 'الأنظمة التي يوقف عطلها الإنتاج أو الإشغال تبرر فترة صيانة أقصر.' } },
      { id: 'unattended', icon: 'network', label: { en: 'Limited site attendance', ar: 'إشراف ميداني محدود' }, body: { en: 'Where nobody checks the plant room daily, scheduled attention replaces observation.', ar: 'حيث لا يتفقد أحد غرفة المعدات يوميًا، تحل العناية المجدولة محل الملاحظة.' } },
    ],
    approach: [
      { id: 'calibrate', icon: 'sensor', label: { en: 'Calibrate and verify sensors', ar: 'معايرة المستشعرات والتحقق منها' }, body: { en: 'Against reference standards, with the pre-calibration reading recorded so drift is visible over time.', ar: 'مقابل معايير مرجعية، مع تسجيل القراءة قبل المعايرة ليصبح الانحراف مرئيًا مع الوقت.' } },
      { id: 'dosing', icon: 'pump', label: { en: 'Service dosing equipment', ar: 'خدمة معدات الضخ' }, body: { en: 'Valves, seals, tubing and calibration of actual delivered volume against the setting.', ar: 'الصمامات والحشوات والخراطيم ومعايرة الحجم المضخوخ فعليًا مقابل الإعداد.' } },
      { id: 'filters', icon: 'filter', label: { en: 'Inspect filtration', ar: 'فحص الترشيح' }, body: { en: 'Element condition, cleaning cycle frequency and differential pressure behaviour.', ar: 'حالة العنصر، وتكرار دورة التنظيف، وسلوك فرق الضغط.' } },
      { id: 'report', icon: 'clipboard', label: { en: 'Record and report', ar: 'التسجيل والتقرير' }, body: { en: 'What was found, what was corrected and what needs attention before the next visit.', ar: 'ما وُجد، وما صُحّح، وما يحتاج عناية قبل الزيارة التالية.' } },
    ],
    deliverables: [
      { en: 'Scheduled service visits to an agreed interval', ar: 'زيارات خدمة مجدولة بفترات متفق عليها' },
      { en: 'Calibration records with pre- and post-adjustment values', ar: 'سجلات معايرة بقيم ما قبل وما بعد الضبط' },
      { en: 'Equipment condition report', ar: 'تقرير حالة المعدات' },
      { en: 'Recommended actions before the next visit', ar: 'إجراءات موصى بها قبل الزيارة التالية' },
    ],
    technologies: ['sensors-measurement', 'chemical-dosing', 'filtration', 'monitoring-control'],
    solutions: ['cooling-water', 'boiler-steam', 'potable-water', 'ro-membranes'],
    cta: { en: 'Request Technical Support', ar: 'اطلب الدعم الفني' },
  },

  {
    slug: 'technical-support',
    status: 'published',
    icon: 'network',
    verb: { en: 'Support', ar: 'ادعم' },
    title: { en: 'Technical Support', ar: 'الدعم الفني' },
    headline: { en: 'Someone Who Knows the System When You Need Them.', ar: 'من يعرف النظام حين تحتاج إليه.' },
    summary: { en: 'Application advice, troubleshooting and escalation for systems already in service.', ar: 'استشارات تطبيقية واستكشاف أعطال وتصعيد للأنظمة القائمة في الخدمة.' },
    metaTitle: { en: 'Water Treatment Technical Support | C-Water', ar: 'الدعم الفني لمعالجة المياه | C-Water' },
    metaDescription: { en: 'Technical support for industrial water treatment systems: troubleshooting, application advice, control review and on-site attendance when needed.', ar: 'دعم فني لأنظمة معالجة المياه الصناعية: استكشاف الأعطال، والاستشارة التطبيقية، ومراجعة التحكم، والحضور الميداني عند الحاجة.' },
    whatItIs: { en: 'Access to engineers who know the application: for a question, for a problem that has not been solved, or for an unplanned event.', ar: 'وصول إلى مهندسين يعرفون التطبيق: لسؤال، أو لمشكلة لم تُحل، أو لحدث غير مخطط.' },
    whyItMatters: { en: 'Most treatment problems are diagnosable from the right questions and the right data. The difficulty is usually knowing which questions to ask.', ar: 'معظم مشكلات المعالجة قابلة للتشخيص من الأسئلة الصحيحة والبيانات الصحيحة. والصعوبة عادةً في معرفة أي الأسئلة يجب طرحها.' },
    whenYouNeedIt: [
      { id: 'problem', icon: 'wrench', label: { en: 'Something is not behaving normally', ar: 'شيء ما لا يعمل بشكل طبيعي' }, body: { en: 'Unexpected consumption, a reading that does not make sense, a result that changed without an obvious cause.', ar: 'استهلاك غير متوقع، أو قراءة غير منطقية، أو نتيجة تغيرت دون سبب واضح.' } },
      { id: 'decision', icon: 'clipboard', label: { en: 'A decision needs technical input', ar: 'قرار يحتاج مدخلًا فنيًا' }, body: { en: 'Compatibility, a proposed change, or whether an observed condition is acceptable.', ar: 'التوافق، أو تغيير مقترح، أو ما إذا كانت حالة ملاحَظة مقبولة.' } },
      { id: 'urgent', icon: 'shield', label: { en: 'An unplanned event', ar: 'حدث غير مخطط' }, body: { en: 'A contamination, a failure or a condition that needs an assessment quickly.', ar: 'تلوث أو عطل أو حالة تحتاج تقييمًا سريعًا.' } },
    ],
    approach: [
      { id: 'define', icon: 'clipboard', label: { en: 'Define the problem', ar: 'تحديد المشكلة' }, body: { en: 'What changed, when, and what was measured. Establishing the timeline usually narrows the cause considerably.', ar: 'ما الذي تغير ومتى وما الذي قيس. وتحديد التسلسل الزمني يضيّق السبب كثيرًا عادةً.' } },
      { id: 'data', icon: 'monitor', label: { en: 'Look at the data', ar: 'النظر في البيانات' }, body: { en: 'Trends, consumption records and analysis history, remotely where a connected system allows it.', ar: 'الاتجاهات وسجلات الاستهلاك وتاريخ التحليل، عن بُعد حيث يسمح نظام متصل بذلك.' } },
      { id: 'attend', icon: 'wrench', label: { en: 'Attend where needed', ar: 'الحضور عند الحاجة' }, body: { en: 'Some things can only be established on site, including the condition of what nobody has opened recently.', ar: 'بعض الأمور لا تُحدَّد إلا في الموقع، ومنها حالة ما لم يفتحه أحد مؤخرًا.' } },
      { id: 'resolve', icon: 'optimize', label: { en: 'Resolve and record', ar: 'الحل والتوثيق' }, body: { en: 'The corrective action and, where it matters, the change that prevents a repeat.', ar: 'الإجراء التصحيحي، وحيث يهم، التغيير الذي يمنع التكرار.' } },
    ],
    deliverables: [
      { en: 'Technical response to the question or fault raised', ar: 'استجابة فنية للسؤال أو العطل المطروح' },
      { en: 'Diagnosis referenced to system data', ar: 'تشخيص مستند إلى بيانات النظام' },
      { en: 'Corrective action and, where relevant, preventive recommendation', ar: 'إجراء تصحيحي، وعند اللزوم توصية وقائية' },
    ],
    technologies: ['monitoring-control', 'water-analysis', 'chemical-dosing', 'automation-remote-monitoring'],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'wastewater', 'specialised-treatment'],
    cta: { en: 'Request Technical Support', ar: 'اطلب الدعم الفني' },
  },

  {
    slug: 'monitoring-reporting',
    status: 'published',
    icon: 'monitor',
    verb: { en: 'Monitor', ar: 'راقِب' },
    title: { en: 'Monitoring & Reporting', ar: 'المراقبة والتقارير' },
    headline: { en: 'A Record You Can Act On.', ar: 'سجل يمكنك التصرف بناءً عليه.' },
    summary: { en: 'Continuous measurement turned into periodic reporting that says what changed and what to do.', ar: 'قياس مستمر يتحول إلى تقارير دورية تبيّن ما تغيّر وما ينبغي فعله.' },
    metaTitle: { en: 'Water Treatment Monitoring & Reporting | C-Water', ar: 'مراقبة معالجة المياه والتقارير | C-Water' },
    metaDescription: { en: 'Monitoring and reporting for water treatment programmes: continuous data capture, trend analysis, control limit compliance and periodic technical reporting.', ar: 'مراقبة وتقارير لبرامج معالجة المياه: التقاط البيانات المستمر، وتحليل الاتجاهات، والالتزام بحدود التحكم، والتقارير الفنية الدورية.' },
    whatItIs: { en: 'Capture of treatment and system data, review against the programme’s control limits, and periodic reporting that turns the record into decisions.', ar: 'التقاط بيانات المعالجة والنظام، ومراجعتها مقابل حدود تحكم البرنامج، وتقارير دورية تحوّل السجل إلى قرارات.' },
    whyItMatters: { en: 'Data that nobody reviews is storage, not monitoring. The value is in someone technical looking at the trend and saying what it means.', ar: 'البيانات التي لا يراجعها أحد تخزين لا مراقبة. والقيمة في أن ينظر مختص فني إلى الاتجاه ويقول ما يعنيه.' },
    whenYouNeedIt: [
      { id: 'evidence', icon: 'clipboard', label: { en: 'Evidence is required', ar: 'الحاجة إلى أدلة' }, body: { en: 'Audit, compliance or internal reporting that needs a documented record of condition.', ar: 'تدقيق أو مطابقة أو تقارير داخلية تحتاج سجلًا موثقًا للحالة.' } },
      { id: 'multi', icon: 'network', label: { en: 'Several systems or sites', ar: 'أنظمة أو مواقع متعددة' }, body: { en: 'Consistent reporting is what makes different systems comparable.', ar: 'التقارير المتسقة هي ما يجعل الأنظمة المختلفة قابلة للمقارنة.' } },
      { id: 'improve', icon: 'optimize', label: { en: 'You want to improve something', ar: 'ترغب في تحسين شيء ما' }, body: { en: 'Without a baseline record, an improvement cannot be demonstrated.', ar: 'بلا سجل أساس، لا يمكن إثبات أي تحسّن.' } },
    ],
    approach: [
      { id: 'capture', icon: 'sensor', label: { en: 'Capture', ar: 'الالتقاط' }, body: { en: 'Controller data, test results and consumption records brought into one place.', ar: 'بيانات وحدات التحكم ونتائج الاختبارات وسجلات الاستهلاك تُجمع في مكان واحد.' } },
      { id: 'review', icon: 'gauge', label: { en: 'Review against limits', ar: 'المراجعة مقابل الحدود' }, body: { en: 'Time within control limits is a more useful measure than an average.', ar: 'الزمن المقضي داخل حدود التحكم مقياس أنفع من المتوسط.' } },
      { id: 'trend', icon: 'monitor', label: { en: 'Trend', ar: 'تتبع الاتجاه' }, body: { en: 'Across enough time to separate a real change from normal variation.', ar: 'عبر مدة كافية للفصل بين تغير حقيقي وتذبذب طبيعي.' } },
      { id: 'report', icon: 'clipboard', label: { en: 'Report with a recommendation', ar: 'التقرير مع توصية' }, body: { en: 'Every report ends with what should happen next, or explicitly that nothing needs to.', ar: 'ينتهي كل تقرير بما ينبغي فعله تاليًا، أو بالتصريح بأن لا شيء يستدعي إجراءً.' } },
    ],
    deliverables: [
      { en: 'Periodic technical report on system condition', ar: 'تقرير فني دوري عن حالة النظام' },
      { en: 'Trend analysis against control limits', ar: 'تحليل اتجاهات مقابل حدود التحكم' },
      { en: 'Consumption and performance summary', ar: 'ملخص الاستهلاك والأداء' },
      { en: 'Recommended actions, prioritised', ar: 'إجراءات موصى بها مرتبة بالأولوية' },
    ],
    technologies: ['monitoring-control', 'automation-remote-monitoring', 'sensors-measurement', 'water-analysis'],
    solutions: ['cooling-water', 'boiler-steam', 'industrial-water', 'wastewater'],
    cta: { en: 'Discuss Monitoring & Reporting', ar: 'ناقش المراقبة والتقارير' },
  },

  {
    slug: 'optimization',
    status: 'published',
    icon: 'optimize',
    verb: { en: 'Optimise', ar: 'حسّن' },
    title: { en: 'Optimization', ar: 'التحسين' },
    headline: { en: 'Improve What Is Already Working.', ar: 'حسّن ما يعمل بالفعل.' },
    summary: { en: 'Finding the margin in a system that is running acceptably but not at its best.', ar: 'إيجاد الهامش في نظام يعمل بشكل مقبول لكن ليس بأفضل ما يمكن.' },
    metaTitle: { en: 'Water Treatment Optimization | C-Water', ar: 'تحسين معالجة المياه | C-Water' },
    metaDescription: { en: 'Water treatment optimisation: reviewing cycles of concentration, chemical consumption, filtration performance and control strategy to improve water, energy and cost outcomes.', ar: 'تحسين معالجة المياه: مراجعة دورات التركيز واستهلاك الكيماويات وأداء الترشيح واستراتيجية التحكم لتحسين نتائج المياه والطاقة والتكلفة.' },
    whatItIs: { en: 'A structured review of an operating system to find where it is running more conservatively, more expensively or less efficiently than the water chemistry actually requires.', ar: 'مراجعة منهجية لنظام قائم لمعرفة أين يعمل بتحفظ أو تكلفة أو كفاءة أقل مما تتطلبه كيمياء المياه فعليًا.' },
    whyItMatters: { en: 'Systems are usually commissioned with conservative settings and then left there. The margin built in for safety at commissioning is often still being paid for years later.', ar: 'تُشغَّل الأنظمة عادةً بإعدادات متحفظة ثم تُترك عليها. والهامش المُدرج للأمان عند التشغيل الابتدائي غالبًا ما يُدفع ثمنه بعد سنوات.' },
    whenYouNeedIt: [
      { id: 'stable', icon: 'gauge', label: { en: 'The system is stable', ar: 'النظام مستقر' }, body: { en: 'Optimisation is for systems that work. Fix instability first, then look for margin.', ar: 'التحسين للأنظمة التي تعمل. عالج عدم الاستقرار أولًا ثم ابحث عن الهامش.' } },
      { id: 'cost', icon: 'energy', label: { en: 'Consumption seems high', ar: 'الاستهلاك يبدو مرتفعًا' }, body: { en: 'Water, chemical or energy use that is out of line with comparable systems is worth investigating.', ar: 'استهلاك المياه أو الكيماويات أو الطاقة غير المتناسب مع أنظمة مماثلة يستحق التحقيق.' } },
      { id: 'target', icon: 'droplet', label: { en: 'A water reduction target', ar: 'هدف لخفض استهلاك المياه' }, body: { en: 'Cycles of concentration and reuse opportunity are usually where the available reduction sits.', ar: 'عادةً ما يكمن الخفض المتاح في دورات التركيز وفرص إعادة الاستخدام.' } },
    ],
    approach: [
      { id: 'baseline', icon: 'clipboard', label: { en: 'Establish the baseline', ar: 'وضع خط الأساس' }, body: { en: 'Current consumption, current control settings and current system condition, measured rather than assumed.', ar: 'الاستهلاك الحالي وإعدادات التحكم الحالية وحالة النظام الحالية، مقاسة لا مفترضة.' } },
      { id: 'limits', icon: 'lab', label: { en: 'Find the real limit', ar: 'إيجاد الحد الحقيقي' }, body: { en: 'What the water chemistry actually permits, as distinct from what the system is currently set to.', ar: 'ما تسمح به كيمياء المياه فعلًا، تمييزًا عمّا ضُبط عليه النظام حاليًا.' } },
      { id: 'change', icon: 'controller', label: { en: 'Change in controlled steps', ar: 'التغيير بخطوات محكومة' }, body: { en: 'Setpoints moved incrementally with monitoring at each step, so a limit is approached rather than discovered.', ar: 'تُنقل نقاط الضبط تدريجيًا مع المراقبة عند كل خطوة، ليُقترب من الحد لا أن يُكتشف فجأة.' } },
      { id: 'confirm', icon: 'optimize', label: { en: 'Confirm and hold', ar: 'التأكيد والتثبيت' }, body: { en: 'The new operating point is verified over time and documented so it survives a staff change.', ar: 'يُتحقق من نقطة التشغيل الجديدة عبر الزمن وتُوثَّق لتصمد أمام تغير الكوادر.' } },
    ],
    deliverables: [
      { en: 'Baseline measurement of current performance', ar: 'قياس أساس للأداء الحالي' },
      { en: 'Identified optimisation opportunities with their constraint', ar: 'فرص تحسين محددة مع القيد الخاص بكل منها' },
      { en: 'Controlled implementation plan', ar: 'خطة تنفيذ محكومة' },
      { en: 'Verified new operating point, documented', ar: 'نقطة تشغيل جديدة مُتحقَّق منها وموثقة' },
    ],
    technologies: ['monitoring-control', 'water-analysis', 'water-treatment-chemicals', 'automation-remote-monitoring', 'filtration'],
    solutions: ['cooling-water', 'boiler-steam', 'ro-membranes', 'industrial-water', 'wastewater'],
    cta: { en: 'Discuss an Optimisation Review', ar: 'ناقش مراجعة للتحسين' },
  },
];

export const serviceBySlug = Object.fromEntries(services.map((s) => [s.slug, s]));
